SpECTRE: TimeSteppers::History< Vars, DerivVars > Class Template Reference
TimeSteppers::History< Vars, DerivVars > Class Template Reference
Time Steppers
History data used by a TimeStepper.
#include <History.hpp>
Public Types
using value_type = Time
using const_reference = const value_type &
using const_iterator = HistoryIterator< Vars, DerivVars >
using difference_type = typename std::iterator_traits< const_iterator >::difference_type
using size_type = size_t
Public Member Functions
History ()=default
History (const History &)=delete
History (History &&)=default
History & operator= (const History &)=delete
History & operator= (History &&)=default
~History ()=default
void insert (Time time, const Vars &value, DerivVars &&deriv) noexcept
Add a new set of values to the end of the history. deriv is either left unchanged or set to a previously inserted deriv value. The different argument types for value and deriv reflect the common use of this class, which wants value to remain unchanged but does not care about deriv.
void insert_initial (Time time, Vars value, DerivVars deriv) noexcept
Add a new set of values to the front of the history. This is often convenient for setting initial data.
void mark_unneeded (const const_iterator &first_needed) noexcept
Mark all data before the passed point in history as unneeded so it can be removed. Calling this directly should not often be necessary, as it is handled internally by the time steppers.
size_type size () const noexcept
size_type capacity () const noexcept
void shrink_to_fit () noexcept
void pup (PUP::er &p) noexcept
const_iterator begin () const noexcept
These iterators directly return the Time of the past values. The other data can be accessed through the iterators using HistoryIterator::value() and HistoryIterator::derivative().
const_iterator end () const noexcept
These iterators directly return the Time of the past values. The other data can be accessed through the iterators using HistoryIterator::value() and HistoryIterator::derivative().
const_iterator cbegin () const noexcept
These iterators directly return the Time of the past values. The other data can be accessed through the iterators using HistoryIterator::value() and HistoryIterator::derivative().
const_iterator cend () const noexcept
These iterators directly return the Time of the past values. The other data can be accessed through the iterators using HistoryIterator::value() and HistoryIterator::derivative().
const_reference operator[] (size_type n) const noexcept
These return the past times. The other data can be accessed through HistoryIterator methods.
const_reference front () const noexcept
These return the past times. The other data can be accessed through HistoryIterator methods.
const_reference back () const noexcept
These return the past times. The other data can be accessed through HistoryIterator methods.
Detailed Description
template<typename Vars, typename DerivVars>
class TimeSteppers::History< Vars, DerivVars >
History data used by a TimeStepper.
Template Parameters
Vars type of variables being integrated
DerivVars type of derivative variables
Member Typedef Documentation
const_iterator
template<typename Vars, typename DerivVars> using TimeSteppers::History< Vars, DerivVars >::const_iterator = HistoryIterator<Vars, DerivVars>
const_reference
template<typename Vars, typename DerivVars> using TimeSteppers::History< Vars, DerivVars >::const_reference = const value_type&
difference_type
template<typename Vars, typename DerivVars> using TimeSteppers::History< Vars, DerivVars >::difference_type = typename std::iterator_traits<const_iterator>::difference_type
size_type
template<typename Vars, typename DerivVars> using TimeSteppers::History< Vars, DerivVars >::size_type = size_t
value_type
template<typename Vars, typename DerivVars> using TimeSteppers::History< Vars, DerivVars >::value_type = Time
Constructor & Destructor Documentation
History() [1/3]
template<typename Vars, typename DerivVars> TimeSteppers::History< Vars, DerivVars >::History () default
History() [2/3]
template<typename Vars, typename DerivVars> TimeSteppers::History< Vars, DerivVars >::History (const History< Vars, DerivVars > &) delete
History() [3/3]
template<typename Vars, typename DerivVars> TimeSteppers::History< Vars, DerivVars >::History (History< Vars, DerivVars > &&) default
~History()
template<typename Vars, typename DerivVars> TimeSteppers::History< Vars, DerivVars >::~History () default
Member Function Documentation
back()
template<typename Vars, typename DerivVars> const_reference TimeSteppers::History< Vars, DerivVars >::back () const inline noexcept
These return the past times. The other data can be accessed through HistoryIterator methods.
begin()
template<typename Vars, typename DerivVars> const_iterator TimeSteppers::History< Vars, DerivVars >::begin () const inline noexcept
These iterators directly return the Time of the past values. The other data can be accessed through the iterators using HistoryIterator::value() and HistoryIterator::derivative().
Referenced by TimeSteppers::History< Vars, DerivVars >::cbegin(), TimeSteppers::History< Vars, DerivVars >::front(), and TimeSteppers::History< Vars, DerivVars >::operator[]().
capacity()
template<typename Vars, typename DerivVars> size_type TimeSteppers::History< Vars, DerivVars >::capacity () const inline noexcept
References TimeSteppers::History< Vars, DerivVars >::shrink_to_fit().
Referenced by TimeSteppers::History< Vars, DerivVars >::size().
cbegin()
template<typename Vars, typename DerivVars> const_iterator TimeSteppers::History< Vars, DerivVars >::cbegin () const inline noexcept
These iterators directly return the Time of the past values. The other data can be accessed through the iterators using HistoryIterator::value() and HistoryIterator::derivative().
References TimeSteppers::History< Vars, DerivVars >::begin().
cend()
template<typename Vars, typename DerivVars> const_iterator TimeSteppers::History< Vars, DerivVars >::cend () const inline noexcept
These iterators directly return the Time of the past values. The other data can be accessed through the iterators using HistoryIterator::value() and HistoryIterator::derivative().
References TimeSteppers::History< Vars, DerivVars >::end().
end()
template<typename Vars, typename DerivVars> const_iterator TimeSteppers::History< Vars, DerivVars >::end () const inline noexcept
These iterators directly return the Time of the past values. The other data can be accessed through the iterators using HistoryIterator::value() and HistoryIterator::derivative().
Referenced by TimeSteppers::History< Vars, DerivVars >::cend().
front()
template<typename Vars, typename DerivVars> const_reference TimeSteppers::History< Vars, DerivVars >::front () const inline noexcept
These return the past times. The other data can be accessed through HistoryIterator methods.
References TimeSteppers::History< Vars, DerivVars >::begin().
insert()
template<typename Vars , typename DerivVars > void TimeSteppers::History< Vars, DerivVars >::insert (Time time, const Vars & value, DerivVars && deriv) noexcept
Add a new set of values to the end of the history. deriv is either left unchanged or set to a previously inserted deriv value. The different argument types for value and deriv reflect the common use of this class, which wants value to remain unchanged but does not care about deriv.
insert_initial()
template<typename Vars , typename DerivVars > void TimeSteppers::History< Vars, DerivVars >::insert_initial (Time time, Vars value, DerivVars deriv) inline noexcept
Add a new set of values to the front of the history. This is often convenient for setting initial data.
mark_unneeded()
template<typename Vars , typename DerivVars > void TimeSteppers::History< Vars, DerivVars >::mark_unneeded (const const_iterator & first_needed) inline noexcept
Mark all data before the passed point in history as unneeded so it can be removed. Calling this directly should not often be necessary, as it is handled internally by the time steppers.
operator=() [1/2]
template<typename Vars, typename DerivVars> History& TimeSteppers::History< Vars, DerivVars >::operator= (const History< Vars, DerivVars > &) delete
operator=() [2/2]
template<typename Vars, typename DerivVars> History& TimeSteppers::History< Vars, DerivVars >::operator= (History< Vars, DerivVars > &&) default
operator[]()
template<typename Vars, typename DerivVars> const_reference TimeSteppers::History< Vars, DerivVars >::operator[] (size_type n) const inline noexcept
These return the past times. The other data can be accessed through HistoryIterator methods.
References TimeSteppers::History< Vars, DerivVars >::begin().
pup()
template<typename Vars, typename DerivVars> void TimeSteppers::History< Vars, DerivVars >::pup (PUP::er & p) inline noexcept
References TimeSteppers::History< Vars, DerivVars >::shrink_to_fit().
shrink_to_fit()
template<typename Vars , typename DerivVars > void TimeSteppers::History< Vars, DerivVars >::shrink_to_fit () inline noexcept
Referenced by TimeSteppers::History< Vars, DerivVars >::capacity(), and TimeSteppers::History< Vars, DerivVars >::pup().
size()
template<typename Vars, typename DerivVars> size_type TimeSteppers::History< Vars, DerivVars >::size () const inline noexcept
References TimeSteppers::History< Vars, DerivVars >::capacity().
The documentation for this class was generated from the following file:
src/Time/History.hpp