SpECTRE: FastFlow Class Reference
FastFlow Class Reference
Surfaces
Fast flow method for finding apparent horizons.
#include <FastFlow.hpp>
Classes
struct AbsTol
struct Alpha
struct Beta
struct DivergenceIter
struct DivergenceTol
struct Flow
struct IterInfo
Holds information about an iteration of the algorithm.
struct MaxIts
struct TruncationTol
Public Types
enum FlowType { FlowType::Jacobi, FlowType::Curvature, FlowType::Fast }
enum Status {
Status::SuccessfulIteration = 0, Status::AbsTol = 1, Status::TruncationTol = 2, Status::MaxIts = -1,
Status::NegativeRadius = -2, Status::DivergenceError = -3
}
using options = tmpl::list< Flow, Alpha, Beta, AbsTol, TruncationTol, DivergenceTol, DivergenceIter, MaxIts >
Public Member Functions
FastFlow (Flow::type flow, Alpha::type alpha, Beta::type beta, AbsTol::type abs_tol, TruncationTol::type trunc_tol, DivergenceTol::type divergence_tol, DivergenceIter::type divergence_iter, MaxIts::type max_its) noexcept
FastFlow () noexcept
FastFlow (const FastFlow &)=default
FastFlow & operator= (const FastFlow &)=default
FastFlow (FastFlow &&) noexcept=default
FastFlow & operator= (FastFlow &&) noexcept=default
~FastFlow ()=default
void pup (PUP::er &p) noexcept
template<typename Frame >
std::pair< Status, IterInfo > iterate_horizon_finder (gsl::not_null< Strahlkorper< Frame > *> current_strahlkorper, const tnsr::II< DataVector, 3, Frame > &upper_spatial_metric, const tnsr::ii< DataVector, 3, Frame > &extrinsic_curvature, const tnsr::Ijj< DataVector, 3, Frame > &christoffel_2nd_kind) noexcept
Evaluate residuals and compute the next iteration. If Status==SuccessfulIteration, then current_strahlkorper is modified and current_iteration() is incremented. Otherwise, we end with success or failure, and neither current_strahlkorper nor current_iteration() is changed.
size_t current_iteration () const noexcept
template<typename Frame >
size_t current_l_mesh (const Strahlkorper< Frame > &strahlkorper) const noexcept
Given a Strahlkorper defined up to some maximum Y_lm l called l_surface, returns a larger value of l, l_mesh, that is used for evaluating convergence.
void reset_for_next_find () noexcept
Resets the finder.
template<typename Frame >
std::pair< FastFlow::Status, FastFlow::IterInfo > iterate_horizon_finder (const gsl::not_null< Strahlkorper< Frame > *> current_strahlkorper, const tnsr::II< DataVector, 3, Frame > &upper_spatial_metric, const tnsr::ii< DataVector, 3, Frame > &extrinsic_curvature, const tnsr::Ijj< DataVector, 3, Frame > &christoffel_2nd_kind) noexcept
Static Public Attributes
static constexpr OptionString help
Friends
bool operator== (const FastFlow &, const FastFlow &) noexcept
Detailed Description
Fast flow method for finding apparent horizons.
Details
Based on https://arxiv.org/abs/gr-qc/9707050
Member Typedef Documentation
options
using FastFlow::options = tmpl::list<Flow, Alpha, Beta, AbsTol, TruncationTol, DivergenceTol, DivergenceIter, MaxIts>
Member Enumeration Documentation
FlowType
enum FastFlow::FlowType strong
Enumerator
Jacobi
Curvature
Fast
Status
enum FastFlow::Status strong
Enumerator
SuccessfulIteration
AbsTol
TruncationTol
MaxIts
NegativeRadius
DivergenceError
Constructor & Destructor Documentation
FastFlow() [1/4]
FastFlow::FastFlow (Flow::type flow, Alpha::type alpha, Beta::type beta, AbsTol::type abs_tol, TruncationTol::type trunc_tol, DivergenceTol::type divergence_tol, DivergenceIter::type divergence_iter, MaxIts::type max_its) noexcept
FastFlow() [2/4]
FastFlow::FastFlow () inline noexcept
FastFlow() [3/4]
FastFlow::FastFlow (const FastFlow &) default
FastFlow() [4/4]
FastFlow::FastFlow (FastFlow &&) default noexcept
~FastFlow()
FastFlow::~FastFlow () default
Member Function Documentation
current_iteration()
size_t FastFlow::current_iteration () const inline noexcept
current_l_mesh()
template<typename Frame > template size_t FastFlow::current_l_mesh (const Strahlkorper< Frame > & strahlkorper) const noexcept
Given a Strahlkorper defined up to some maximum Y_lm l called l_surface, returns a larger value of l, l_mesh, that is used for evaluating convergence.
References StrahlkorperGr::inverse_surface_metric(), and square().
Referenced by create_from_yaml< FastFlow::FlowType >::create().
iterate_horizon_finder() [1/2]
template<typename Frame > std::pair<FastFlow::Status, FastFlow::IterInfo> FastFlow::iterate_horizon_finder (const gsl::not_null< Strahlkorper< Frame > *> current_strahlkorper, const tnsr::II< DataVector, 3, Frame > & upper_spatial_metric, const tnsr::ii< DataVector, 3, Frame > & extrinsic_curvature, const tnsr::Ijj< DataVector, 3, Frame > & christoffel_2nd_kind) noexcept
References db::create(), and magnitude().
iterate_horizon_finder() [2/2]
template<typename Frame > std::pair<Status, IterInfo> FastFlow::iterate_horizon_finder (gsl::not_null< Strahlkorper< Frame > *> current_strahlkorper, const tnsr::II< DataVector, 3, Frame > & upper_spatial_metric, const tnsr::ii< DataVector, 3, Frame > & extrinsic_curvature, const tnsr::Ijj< DataVector, 3, Frame > & christoffel_2nd_kind) noexcept
Evaluate residuals and compute the next iteration. If Status==SuccessfulIteration, then current_strahlkorper is modified and current_iteration() is incremented. Otherwise, we end with success or failure, and neither current_strahlkorper nor current_iteration() is changed.
operator=() [1/2]
FastFlow& FastFlow::operator= (const FastFlow &) default
operator=() [2/2]
FastFlow& FastFlow::operator= (FastFlow &&) default noexcept
pup()
void FastFlow::pup (PUP::er & p) noexcept
reset_for_next_find()
void FastFlow::reset_for_next_find () inline noexcept
Resets the finder.
References operator==().
Friends And Related Function Documentation
operator==
bool operator== (const FastFlow & lhs, const FastFlow & rhs) friend
Member Data Documentation
help
constexpr OptionString FastFlow::help static
Initial value:
{
      "Find a Strahlkorper using a 'fast flow' method.\n"
      "Based on Gundlach, PRD 57, 863 (1998).\n"
      "Expands the surface in terms of spherical harmonics Y_lm up to a given\n"
      "l_surface, and varies the coefficients S_lm where 0<=l<=l_surface to\n"
      "minimize the residual of the apparent horizon equation.  Also keeps\n"
      "another representation of the surface that is expanded up to\n"
      "l_mesh > l_surface.  Let R_{Y_lm} be the residual computed using the\n"
      "surface represented up to l_surface; this residual can in principle be\n"
      "lowered to machine roundoff by enough iterations. Let R_{mesh} be the\n"
      "residual computed using the surface represented up to l_mesh; this\n"
      "residual represents the truncation error, since l_mesh>l_surface and\n"
      "since coefficients S_lm with l>l_surface are not modified in the\n"
      "iteration.\n\n"
      "Convergence is achieved if R_{Y_lm}< TruncationTol*R_{mesh}, or if\n"
      "R_{Y_lm}<AbsTol, where TruncationTol and AbsTol are input parameters.\n"
      "If instead |R_{mesh}|_i > DivergenceTol * min_{j}(|R_{mesh}|_j) where\n"
      "i is the iteration index and j runs from 0 to i-DivergenceIter, then\n"
      "FastFlow exits with Status::DivergenceError.  Here DivergenceIter and\n"
      "DivergenceTol are input parameters."}
The documentation for this class was generated from the following files:
src/ApparentHorizons/FastFlow.hpp
src/ApparentHorizons/FastFlow.cpp