SpECTRE: ElementMap< Dim, TargetFrame > Class Template Reference
ElementMap< Dim, TargetFrame > Class Template Reference
Computational Domain
The CoordinateMap for the Element from the Logical frame to the TargetFrame
#include <ElementMap.hpp>
Public Types
using source_frame = Frame::Logical
using target_frame = TargetFrame
Public Member Functions
ElementMap (ElementId< Dim > element_id, std::unique_ptr< CoordinateMapBase< Frame::Logical, TargetFrame, Dim >> block_map) noexcept
const CoordinateMapBase< Frame::Logical, TargetFrame, Dim > & block_map () const noexcept
const ElementId< Dim > & element_id () const noexcept
template<typename T >
tnsr::I< T, Dim, TargetFrame > operator() (tnsr::I< T, Dim, Frame::Logical > source_point) const noexcept
template<typename T >
tnsr::I< T, Dim, Frame::Logical > inverse (tnsr::I< T, Dim, TargetFrame > target_point) const noexcept
template<typename T >
Tensor< T, tmpl::integral_list< std::int32_t, 2, 1 >, index_list< SpatialIndex< Dim, UpLo::Up, Frame::Logical >, SpatialIndex< Dim, UpLo::Lo, TargetFrame > > > inv_jacobian (tnsr::I< T, Dim, Frame::Logical > source_point) const noexcept
template<typename T >
Tensor< T, tmpl::integral_list< std::int32_t, 2, 1 >, index_list< SpatialIndex< Dim, UpLo::Up, TargetFrame >, SpatialIndex< Dim, UpLo::Lo, Frame::Logical > > > jacobian (tnsr::I< T, Dim, Frame::Logical > source_point) const noexcept
void pup (PUP::er &p) noexcept
Static Public Attributes
static constexpr size_t dim = Dim
Detailed Description
template<size_t Dim, typename TargetFrame>
class ElementMap< Dim, TargetFrame >
The CoordinateMap for the Element from the Logical frame to the TargetFrame
An ElementMap takes a CoordinateMap for a Block and an ElementId as input, and then "prepends" the correct affine map to the CoordinateMap so that the map corresponds to the coordinate map for the Element rather than the Block. This allows DomainCreators to only specify the maps for the Blocks without worrying about how the domain may be decomposed beyond that.
Member Typedef Documentation
source_frame
template<size_t Dim, typename TargetFrame> using ElementMap< Dim, TargetFrame >::source_frame = Frame::Logical
target_frame
template<size_t Dim, typename TargetFrame> using ElementMap< Dim, TargetFrame >::target_frame = TargetFrame
Constructor & Destructor Documentation
ElementMap()
template<size_t Dim, typename TargetFrame> ElementMap< Dim, TargetFrame >::ElementMap (ElementId< Dim > element_id, std::unique_ptr< CoordinateMapBase< Frame::Logical, TargetFrame, Dim >> block_map) noexcept
Member Function Documentation
block_map()
template<size_t Dim, typename TargetFrame> const CoordinateMapBase<Frame::Logical, TargetFrame, Dim>& ElementMap< Dim, TargetFrame >::block_map () const inline noexcept
element_id()
template<size_t Dim, typename TargetFrame> const ElementId<Dim>& ElementMap< Dim, TargetFrame >::element_id () const inline noexcept
inv_jacobian()
template<size_t Dim, typename TargetFrame> template<typename T > Tensor<T, tmpl::integral_list<std::int32_t, 2, 1>, index_list<SpatialIndex<Dim, UpLo::Up, Frame::Logical>, SpatialIndex<Dim, UpLo::Lo, TargetFrame> > > ElementMap< Dim, TargetFrame >::inv_jacobian (tnsr::I< T, Dim, Frame::Logical > source_point) const inline noexcept
References gsl::at().
inverse()
template<size_t Dim, typename TargetFrame> template<typename T > tnsr::I<T, Dim, Frame::Logical> ElementMap< Dim, TargetFrame >::inverse (tnsr::I< T, Dim, TargetFrame > target_point) const inline noexcept
References gsl::at().
jacobian()
template<size_t Dim, typename TargetFrame> template<typename T > Tensor<T, tmpl::integral_list<std::int32_t, 2, 1>, index_list<SpatialIndex<Dim, UpLo::Up, TargetFrame>, SpatialIndex<Dim, UpLo::Lo, Frame::Logical> > > ElementMap< Dim, TargetFrame >::jacobian (tnsr::I< T, Dim, Frame::Logical > source_point) const inline noexcept
References gsl::at(), ElementMap< Dim, TargetFrame >::pup(), and std::numeric_limits::signaling_NaN().
operator()()
template<size_t Dim, typename TargetFrame> template<typename T > tnsr::I<T, Dim, TargetFrame> ElementMap< Dim, TargetFrame >::operator() (tnsr::I< T, Dim, Frame::Logical > source_point) const inline noexcept
pup()
template<size_t Dim, typename TargetFrame> void ElementMap< Dim, TargetFrame >::pup (PUP::er & p) noexcept
Referenced by ElementMap< Dim, TargetFrame >::jacobian().
Member Data Documentation
dim
template<size_t Dim, typename TargetFrame> constexpr size_t ElementMap< Dim, TargetFrame >::dim = Dim static
The documentation for this class was generated from the following file:
src/Domain/ElementMap.hpp