SpECTRE: MathFunctions::TensorProduct< Dim > Class Template Reference
MathFunctions::TensorProduct< Dim > Class Template Reference
Math Functions
a tensor product of one-dimensional MathFunctions
#include <TensorProduct.hpp>
Public Member Functions
TensorProduct (double scale, std::array< std::unique_ptr< MathFunction< 1 >>, Dim > &&functions)
TensorProduct (const TensorProduct &)=delete
TensorProduct (TensorProduct &&)=default
TensorProduct & operator= (const TensorProduct &)=delete
TensorProduct & operator= (TensorProduct &&)=default
~TensorProduct ()=default
template<typename T >
Scalar< T > operator() (const tnsr::I< T, Dim > &x) const noexcept
The value of the function.
template<typename T >
tnsr::i< T, Dim > first_derivatives (const tnsr::I< T, Dim > &x) const noexcept
The partial derivatives of the function.
template<typename T >
tnsr::ii< T, Dim > second_derivatives (const tnsr::I< T, Dim > &x) const noexcept
The second partial derivatives of the function.
Detailed Description
template<size_t Dim>
class MathFunctions::TensorProduct< Dim >
a tensor product of one-dimensional MathFunctions
Constructor & Destructor Documentation
TensorProduct() [1/3]
template<size_t Dim> MathFunctions::TensorProduct< Dim >::TensorProduct (double scale, std::array< std::unique_ptr< MathFunction< 1 >>, Dim > && functions)
TensorProduct() [2/3]
template<size_t Dim> MathFunctions::TensorProduct< Dim >::TensorProduct (const TensorProduct< Dim > &) delete
TensorProduct() [3/3]
template<size_t Dim> MathFunctions::TensorProduct< Dim >::TensorProduct (TensorProduct< Dim > &&) default
~TensorProduct()
template<size_t Dim> MathFunctions::TensorProduct< Dim >::~TensorProduct () default
Member Function Documentation
first_derivatives()
template<size_t Dim> template<typename T > tnsr::i< T, Dim > MathFunctions::TensorProduct< Dim >::first_derivatives (const tnsr::I< T, Dim > & x) const noexcept
The partial derivatives of the function.
References gsl::at().
operator()()
template<size_t Dim> template<typename T > Scalar< T > MathFunctions::TensorProduct< Dim >::operator() (const tnsr::I< T, Dim > & x) const noexcept
The value of the function.
References gsl::at().
operator=() [1/2]
template<size_t Dim> TensorProduct& MathFunctions::TensorProduct< Dim >::operator= (const TensorProduct< Dim > &) delete
operator=() [2/2]
template<size_t Dim> TensorProduct& MathFunctions::TensorProduct< Dim >::operator= (TensorProduct< Dim > &&) default
second_derivatives()
template<size_t Dim> template<typename T > tnsr::ii< T, Dim > MathFunctions::TensorProduct< Dim >::second_derivatives (const tnsr::I< T, Dim > & x) const noexcept
The second partial derivatives of the function.
References gsl::at(), and GENERATE_INSTANTIATIONS.
The documentation for this class was generated from the following files:
src/PointwiseFunctions/MathFunctions/TensorProduct.hpp
src/PointwiseFunctions/MathFunctions/TensorProduct.cpp