SpECTRE: Strahlkorper< Frame > Class Template Reference
Strahlkorper< Frame > Class Template Reference
Surfaces
A star-shaped surface expanded in spherical harmonics.
#include <FastFlow.hpp>
Public Member Functions
Strahlkorper ()=default
Strahlkorper (size_t l_max, size_t m_max, double radius, std::array< double, 3 > center) noexcept
Construct a sphere of radius radius with a given center.
Strahlkorper (size_t l_max, size_t m_max, const DataVector &radius_at_collocation_points, std::array< double, 3 > center) noexcept
Construct a Strahlkorper from a DataVector containing the radius at the collocation points.
Strahlkorper (size_t l_max, size_t m_max, const Strahlkorper &another_strahlkorper) noexcept
Prolong or restrict another surface to the given l_max and m_max.
Strahlkorper (DataVector coefs, const Strahlkorper &another_strahlkorper) noexcept
Construct a Strahlkorper from another Strahlkorper, but explicitly specifying the coefficients. Here coefficients are in the same storage scheme as the coefficients() member function returns.
Strahlkorper (DataVector coefs, Strahlkorper &&another_strahlkorper) noexcept
Move-construct a Strahlkorper from another Strahlkorper, explicitly specifying the coefficients.
void pup (PUP::er &p) noexcept
Serialization for Charm++.
const DataVector & coefficients () const noexcept
DataVector & coefficients () noexcept
const std::array< double, 3 > & center () const noexcept
Point about which the spectral basis of the Strahlkorper is expanded. The center is given in the frame in which the Strahlkorper is defined. This center must be somewhere inside the Strahlkorper, but in principle it can be anywhere. See physical_center() for a different measure.
std::array< double, 3 > physical_center () const noexcept
Approximate physical center (determined by \(l=1\) coefficients) Implementation of Eqs. (38)-(40) in Hemberger et al, arXiv:1211.6079
double average_radius () const noexcept
Average radius of the surface (determined by \(Y_{00}\) coefficient)
size_t l_max () const noexcept
Maximum \(l\) in \(Y_{lm}\) decomposition.
size_t m_max () const noexcept
Maximum \(m\) in \(Y_{lm}\) decomposition.
double radius (double theta, double phi) const noexcept
Radius at a particular angle \((\theta,\phi)\). This is inefficient if done at multiple points many times. See YlmSpherepack for alternative ways of computing this.
bool point_is_contained (const std::array< double, 3 > &x) const noexcept
Determine if a point x is contained inside the surface. The point must be given in Cartesian coordinates in the frame in which the Strahlkorper is defined. This is inefficient if done at multiple points many times.
const YlmSpherepack & ylm_spherepack () const noexcept
Detailed Description
template<typename Frame>
class Strahlkorper< Frame >
A star-shaped surface expanded in spherical harmonics.
Constructor & Destructor Documentation
Strahlkorper() [1/6]
template<typename Frame> Strahlkorper< Frame >::Strahlkorper () default
Strahlkorper() [2/6]
template<typename Frame > Strahlkorper< Frame >::Strahlkorper (size_t l_max, size_t m_max, double radius, std::array< double, 3 > center) noexcept
Construct a sphere of radius radius with a given center.
Strahlkorper() [3/6]
template<typename Frame > Strahlkorper< Frame >::Strahlkorper (size_t l_max, size_t m_max, const DataVector & radius_at_collocation_points, std::array< double, 3 > center) noexcept
Construct a Strahlkorper from a DataVector containing the radius at the collocation points.
References ASSERT.
Strahlkorper() [4/6]
template<typename Frame > Strahlkorper< Frame >::Strahlkorper (size_t l_max, size_t m_max, const Strahlkorper< Frame > & another_strahlkorper) noexcept
Prolong or restrict another surface to the given l_max and m_max.
Strahlkorper() [5/6]
template<typename Frame > Strahlkorper< Frame >::Strahlkorper (DataVector coefs, const Strahlkorper< Frame > & another_strahlkorper) noexcept
Construct a Strahlkorper from another Strahlkorper, but explicitly specifying the coefficients. Here coefficients are in the same storage scheme as the coefficients() member function returns.
References ASSERT.
Strahlkorper() [6/6]
template<typename Frame > Strahlkorper< Frame >::Strahlkorper (DataVector coefs, Strahlkorper< Frame > && another_strahlkorper) noexcept
Move-construct a Strahlkorper from another Strahlkorper, explicitly specifying the coefficients.
References ASSERT.
Member Function Documentation
average_radius()
template<typename Frame > double Strahlkorper< Frame >::average_radius () const noexcept
Average radius of the surface (determined by \(Y_{00}\) coefficient)
center()
template<typename Frame> const std::array<double, 3>& Strahlkorper< Frame >::center () const inline noexcept
Point about which the spectral basis of the Strahlkorper is expanded. The center is given in the frame in which the Strahlkorper is defined. This center must be somewhere inside the Strahlkorper, but in principle it can be anywhere. See physical_center() for a different measure.
coefficients() [1/2]
template<typename Frame> const DataVector& Strahlkorper< Frame >::coefficients () const inline noexcept
These coefficients are stored as SPHEREPACK coefficients. Suppose you represent a set of coefficients \(F^{lm}\) in the expansion
\[ f(\theta,\phi) = \sum_{l=0}^{l_{max}} \sum_{m=-l}^{l} F^{lm} Y^{lm}(\theta,\phi) \]
Here the \(Y^{lm}(\theta,\phi)\) are the usual complex-valued scalar spherical harmonics, so \(F^{lm}\) are also complex-valued. But here we assume that \(f(\theta,\phi)\) is real, so therefore the \(F^{lm}\) obey \(F^{l-m} = (-1)^m (F^{lm})^\star\). So one does not need to store both real and imaginary parts for both positive and negative \(m\), and the stored coefficients can all be real.
So the stored coefficients are:
\begin{align} \text{coefficients()(l,m)} &= (-1)^m \sqrt{\frac{2}{\pi}} \Re(F^{lm}) \quad \text{for} \quad m\ge 0, \\ \text{coefficients()(l,m)} &= (-1)^m \sqrt{\frac{2}{\pi}} \Im(F^{lm}) \quad \text{for} \quad m<0 \end{align}
coefficients() [2/2]
template<typename Frame> DataVector& Strahlkorper< Frame >::coefficients () inline noexcept
l_max()
template<typename Frame> size_t Strahlkorper< Frame >::l_max () const inline noexcept
Maximum \(l\) in \(Y_{lm}\) decomposition.
m_max()
template<typename Frame> size_t Strahlkorper< Frame >::m_max () const inline noexcept
Maximum \(m\) in \(Y_{lm}\) decomposition.
References GeneralizedHarmonic::phi().
physical_center()
template<typename Frame > std::array< double, 3 > Strahlkorper< Frame >::physical_center () const noexcept
Approximate physical center (determined by \(l=1\) coefficients) Implementation of Eqs. (38)-(40) in Hemberger et al, arXiv:1211.6079
References SpherepackIterator::set().
point_is_contained()
template<typename Frame > bool Strahlkorper< Frame >::point_is_contained (const std::array< double, 3 > & x) const noexcept
Determine if a point x is contained inside the surface. The point must be given in Cartesian coordinates in the frame in which the Strahlkorper is defined. This is inefficient if done at multiple points many times.
References magnitude(), and GeneralizedHarmonic::phi().
pup()
template<typename Frame > void Strahlkorper< Frame >::pup (PUP::er & p) noexcept
Serialization for Charm++.
radius()
template<typename Frame > double Strahlkorper< Frame >::radius (double theta, double phi) const noexcept
Radius at a particular angle \((\theta,\phi)\). This is inefficient if done at multiple points many times. See YlmSpherepack for alternative ways of computing this.
References GeneralizedHarmonic::phi().
ylm_spherepack()
template<typename Frame> const YlmSpherepack& Strahlkorper< Frame >::ylm_spherepack () const inline noexcept
The documentation for this class was generated from the following files:
src/ApparentHorizons/FastFlow.hpp
src/ApparentHorizons/Strahlkorper.hpp
src/ApparentHorizons/Strahlkorper.cpp