SpECTRE: DomainCreators::Shell< TargetFrame > Class Template Reference
DomainCreators::Shell< TargetFrame > Class Template Reference
Domain Creators
Create a 3D Domain in the shape of a hollow spherical shell consisting of six wedges.
#include <DomainCreator.hpp>
Classes
struct InitialGridPoints
struct InitialRefinement
struct InnerRadius
struct OuterRadius
struct UseEquiangularMap
Public Types
using options = tmpl::list< InnerRadius, OuterRadius, InitialRefinement, InitialGridPoints, UseEquiangularMap >
Public Types inherited from DomainCreator< 3, TargetFrame >
using creatable_classes = typename DomainCreators_detail::domain_creators< VolumeDim >::template creators< TargetFrame >
Public Member Functions
Shell (typename InnerRadius::type inner_radius, typename OuterRadius::type outer_radius, typename InitialRefinement::type initial_refinement, typename InitialGridPoints::type initial_number_of_grid_points, typename UseEquiangularMap::type use_equiangular_map) noexcept
Shell ()=default
Shell (const Shell &)=delete
Shell (Shell &&) noexcept=default
Shell & operator= (const Shell &)=delete
Shell & operator= (Shell &&) noexcept=default
~Shell () noexcept override=default
Domain< 3, TargetFrame > create_domain () const noexcept override
std::vector< std::array< size_t, 3 > > initial_extents () const noexcept override
Obtain the initial grid extents of the block with the given index.
std::vector< std::array< size_t, 3 > > initial_refinement_levels () const noexcept override
Obtain the initial refinement levels of the blocks.
Public Member Functions inherited from DomainCreator< 3, TargetFrame >
DomainCreator ()=default
DomainCreator (const DomainCreator< VolumeDim, TargetFrame > &)=delete
DomainCreator (DomainCreator< VolumeDim, TargetFrame > &&) noexcept=default
DomainCreator< VolumeDim, TargetFrame > & operator= (const DomainCreator< VolumeDim, TargetFrame > &)=delete
DomainCreator< VolumeDim, TargetFrame > & operator= (DomainCreator< VolumeDim, TargetFrame > &&) noexcept=default
virtual ~DomainCreator ()=default
Static Public Attributes
static constexpr OptionString help
Detailed Description
template<typename TargetFrame>
class DomainCreators::Shell< TargetFrame >
Create a 3D Domain in the shape of a hollow spherical shell consisting of six wedges.
Member Typedef Documentation
options
template<typename TargetFrame > using DomainCreators::Shell< TargetFrame >::options = tmpl::list<InnerRadius, OuterRadius, InitialRefinement, InitialGridPoints, UseEquiangularMap>
Constructor & Destructor Documentation
Shell() [1/4]
template<typename TargetFrame > DomainCreators::Shell< TargetFrame >::Shell (typename InnerRadius::type inner_radius, typename OuterRadius::type outer_radius, typename InitialRefinement::type initial_refinement, typename InitialGridPoints::type initial_number_of_grid_points, typename UseEquiangularMap::type use_equiangular_map) noexcept
Shell() [2/4]
template<typename TargetFrame > DomainCreators::Shell< TargetFrame >::Shell () default
Shell() [3/4]
template<typename TargetFrame > DomainCreators::Shell< TargetFrame >::Shell (const Shell< TargetFrame > &) delete
Shell() [4/4]
template<typename TargetFrame > DomainCreators::Shell< TargetFrame >::Shell (Shell< TargetFrame > &&) default noexcept
~Shell()
template<typename TargetFrame > DomainCreators::Shell< TargetFrame >::~Shell () override default noexcept
Member Function Documentation
create_domain()
template<typename TargetFrame > Domain< 3, TargetFrame > DomainCreators::Shell< TargetFrame >::create_domain () const override virtual noexcept
Implements DomainCreator< 3, TargetFrame >.
References Direction< VolumeDim >::lower_eta(), Direction< VolumeDim >::lower_xi(), Direction< VolumeDim >::lower_zeta(), Direction< VolumeDim >::upper_eta(), Direction< VolumeDim >::upper_xi(), and Direction< VolumeDim >::upper_zeta().
initial_extents()
template<typename TargetFrame > std::vector< std::array< size_t, 3 > > DomainCreators::Shell< TargetFrame >::initial_extents () const override virtual noexcept
Obtain the initial grid extents of the block with the given index.
Implements DomainCreator< 3, TargetFrame >.
initial_refinement_levels()
template<typename TargetFrame > std::vector< std::array< size_t, 3 > > DomainCreators::Shell< TargetFrame >::initial_refinement_levels () const override virtual noexcept
Obtain the initial refinement levels of the blocks.
Implements DomainCreator< 3, TargetFrame >.
operator=() [1/2]
template<typename TargetFrame > Shell& DomainCreators::Shell< TargetFrame >::operator= (const Shell< TargetFrame > &) delete
operator=() [2/2]
template<typename TargetFrame > Shell& DomainCreators::Shell< TargetFrame >::operator= (Shell< TargetFrame > &&) default noexcept
Member Data Documentation
help
template<typename TargetFrame > constexpr OptionString DomainCreators::Shell< TargetFrame >::help static
Initial value:
{
      "Creates a 3D spherical shell with 6 Blocks. `UseEquiangularMap` has\n"
      "a default value of `true` because there is no central Block in this\n"
      "domain. Equidistant coordinates are best suited to Blocks with\n"
      "Cartesian grids. However, the option is allowed for testing "
      "purposes.\n"}
The documentation for this class was generated from the following files:
src/Domain/DomainCreators/DomainCreator.hpp
src/Domain/DomainCreators/Shell.hpp
src/Domain/DomainCreators/Shell.cpp