SpECTRE: CoordinateMaps::Equiangular Class Reference
CoordinateMaps::Equiangular Class Reference
Coordinate Maps
Non-linear map from \(\xi \in [A, B]\rightarrow x \in [a, b]\).
#include <Equiangular.hpp>
Public Member Functions
Equiangular (double A, double B, double a, double b) noexcept
Equiangular ()=default
~Equiangular ()=default
Equiangular (const Equiangular &)=default
Equiangular (Equiangular &&) noexcept=default
Equiangular & operator= (const Equiangular &)=default
Equiangular & operator= (Equiangular &&)=default
template<typename T >
std::array< tt::remove_cvref_wrap_t< T >, 1 > operator() (const std::array< T, 1 > &source_coords) const noexcept
template<typename T >
std::array< tt::remove_cvref_wrap_t< T >, 1 > inverse (const std::array< T, 1 > &target_coords) const noexcept
template<typename T >
tnsr::Ij< tt::remove_cvref_wrap_t< T >, 1, Frame::NoFrame > jacobian (const std::array< T, 1 > &source_coords) const noexcept
template<typename T >
tnsr::Ij< tt::remove_cvref_wrap_t< T >, 1, Frame::NoFrame > inv_jacobian (const std::array< T, 1 > &source_coords) const noexcept
void pup (PUP::er &p) noexcept
Static Public Attributes
static constexpr size_t dim = 1
Friends
bool operator== (const Equiangular &lhs, const Equiangular &rhs) noexcept
Detailed Description
Non-linear map from \(\xi \in [A, B]\rightarrow x \in [a, b]\).
The formula for the mapping is:
\begin{align} x &= \frac{a}{2} \left(1-\mathrm{tan}\left(\frac{\pi(2\xi-B-A)}{4(B-A)}\right)\right) + \frac{b}{2} \left(1+\mathrm{tan}\left(\frac{\pi(2\xi-B-A)}{4(B-A)}\right)\right)\\ \xi &= \frac{A}{2} \left(1-\frac{4}{\pi}\mathrm{arctan}\left(\frac{2x-a-b}{b-a}\right)\right)+ \frac{B}{2} \left(1+\frac{4}{\pi}\mathrm{arctan}\left(\frac{2x-a-b}{b-a}\right)\right) \end{align}
Note
The intermediate step in which a tangent map is applied can be more clearly understood if we define the coordinates:
\begin{align} \xi_{logical} &:= \frac{2\xi-B-A}{B-A} \in [-1, 1]\\ \Xi &:= \mathrm{tan}\left(\frac{\pi\xi_{logical}}{4}\right) \in [-1, 1] \end{align}
This map is intended to be used with Wedge2D and Wedge3D when equiangular coordinates are chosen for those maps. For more information on this choice of coordinates, see the documentation for Wedge3D.
Constructor & Destructor Documentation
Equiangular() [1/4]
CoordinateMaps::Equiangular::Equiangular (double A, double B, double a, double b) noexcept
Equiangular() [2/4]
CoordinateMaps::Equiangular::Equiangular () default
~Equiangular()
CoordinateMaps::Equiangular::~Equiangular () default
Equiangular() [3/4]
CoordinateMaps::Equiangular::Equiangular (const Equiangular &) default
Equiangular() [4/4]
CoordinateMaps::Equiangular::Equiangular (Equiangular &&) default noexcept
Member Function Documentation
inv_jacobian()
template<typename T > tnsr::Ij< tt::remove_cvref_wrap_t< T >, 1, Frame::NoFrame > CoordinateMaps::Equiangular::inv_jacobian (const std::array< T, 1 > & source_coords) const noexcept
References dereference_wrapper(), and square().
inverse()
template<typename T > std::array< tt::remove_cvref_wrap_t< T >, 1 > CoordinateMaps::Equiangular::inverse (const std::array< T, 1 > & target_coords) const noexcept
jacobian()
template<typename T > tnsr::Ij< tt::remove_cvref_wrap_t< T >, 1, Frame::NoFrame > CoordinateMaps::Equiangular::jacobian (const std::array< T, 1 > & source_coords) const noexcept
References dereference_wrapper(), and square().
operator()()
template<typename T > std::array< tt::remove_cvref_wrap_t< T >, 1 > CoordinateMaps::Equiangular::operator() (const std::array< T, 1 > & source_coords) const noexcept
operator=() [1/2]
Equiangular& CoordinateMaps::Equiangular::operator= (const Equiangular &) default
operator=() [2/2]
Equiangular& CoordinateMaps::Equiangular::operator= (Equiangular &&) default
pup()
void CoordinateMaps::Equiangular::pup (PUP::er & p) noexcept
Friends And Related Function Documentation
operator==
bool operator== (const Equiangular & lhs, const Equiangular & rhs) friend
Member Data Documentation
dim
constexpr size_t CoordinateMaps::Equiangular::dim = 1 static
The documentation for this class was generated from the following files:
src/Domain/CoordinateMaps/Equiangular.hpp
src/Domain/CoordinateMaps/Equiangular.cpp