SpECTRE: ActionTesting::ActionRunner< Metavariables > Class Template Reference
ActionTesting::ActionRunner< Metavariables > Class Template Reference
Testing Framework
A class that mocks the infrastructure needed to run actions. It simulates message passing using the inbox infrastructure and handles most of the arguments to the apply and is_ready action methods.
#include <ActionTesting.hpp>
Public Types
using ConstGlobalCache_t = Parallel::ConstGlobalCache< Metavariables >
using CacheTuple_t = tuples::TaggedTupleTypelist< typename ConstGlobalCache_t::tag_list >
Public Member Functions
ActionRunner (const ActionRunner &)=delete
ActionRunner (ActionRunner &&)=delete
ActionRunner & operator= (const ActionRunner &)=delete
ActionRunner & operator= (ActionRunner &&)=delete
~ActionRunner ()=default
ActionRunner (CacheTuple_t cache_contents)
Construct from the tuple of ConstGlobalCache objects.
template<typename Component , typename Action , typename DbTags >
bool is_ready (const db::DataBox< DbTags > &box, const typename Component::index &array_index) noexcept
Call Action::is_ready as if on the portion of Component labeled by array_index.
template<typename Component >
std::unordered_map< typename Component::index, tuples::TaggedTupleTypelist< Parallel::get_inbox_tags< typename Component::action_list > > > & inboxes () noexcept
Access the inboxes for a given component.
template<typename Component , typename InboxTag >
std::unordered_set< typename Component::index > nonempty_inboxes () noexcept
Find the set of array indices on Component where the specified inbox is not empty.
template<typename Component >
auto & algorithms () noexcept
Access the mocked algorithms for a component, indexed by array index.
template<typename Component , typename Action , typename DbTags , typename... Args>
decltype(auto) apply (db::DataBox< DbTags > &box, const typename Component::index &array_index, Args &&... args) noexcept
Call Action::apply as if on the portion of Component labeled by array_index.
template<typename Component , typename Action , typename DbTags , typename... Args>
decltype(auto) apply (const db::DataBox< DbTags > &box, const typename Component::index &array_index, Args &&... args) noexcept
Call Action::apply as if on the portion of Component labeled by array_index.
Detailed Description
template<typename Metavariables>
class ActionTesting::ActionRunner< Metavariables >
A class that mocks the infrastructure needed to run actions. It simulates message passing using the inbox infrastructure and handles most of the arguments to the apply and is_ready action methods.
Member Typedef Documentation
CacheTuple_t
template<typename Metavariables > using ActionTesting::ActionRunner< Metavariables >::CacheTuple_t = tuples::TaggedTupleTypelist<typename ConstGlobalCache_t::tag_list>
ConstGlobalCache_t
template<typename Metavariables > using ActionTesting::ActionRunner< Metavariables >::ConstGlobalCache_t = Parallel::ConstGlobalCache<Metavariables>
Constructor & Destructor Documentation
ActionRunner() [1/3]
template<typename Metavariables > ActionTesting::ActionRunner< Metavariables >::ActionRunner (const ActionRunner< Metavariables > &) delete
ActionRunner() [2/3]
template<typename Metavariables > ActionTesting::ActionRunner< Metavariables >::ActionRunner (ActionRunner< Metavariables > &&) delete
~ActionRunner()
template<typename Metavariables > ActionTesting::ActionRunner< Metavariables >::~ActionRunner () default
ActionRunner() [3/3]
template<typename Metavariables > ActionTesting::ActionRunner< Metavariables >::ActionRunner (CacheTuple_t cache_contents) inline explicit
Construct from the tuple of ConstGlobalCache objects.
References tuples::get().
Member Function Documentation
algorithms()
template<typename Metavariables > template<typename Component > auto& ActionTesting::ActionRunner< Metavariables >::algorithms () inline noexcept
Access the mocked algorithms for a component, indexed by array index.
apply() [1/2]
template<typename Metavariables > template<typename Component , typename Action , typename DbTags , typename... Args> decltype(auto) ActionTesting::ActionRunner< Metavariables >::apply (db::DataBox< DbTags > & box, const typename Component::index & array_index, Args &&... args) inline noexcept
Call Action::apply as if on the portion of Component labeled by array_index.
References db::apply().
apply() [2/2]
template<typename Metavariables > template<typename Component , typename Action , typename DbTags , typename... Args> decltype(auto) ActionTesting::ActionRunner< Metavariables >::apply (const db::DataBox< DbTags > & box, const typename Component::index & array_index, Args &&... args) inline noexcept
Call Action::apply as if on the portion of Component labeled by array_index.
References db::apply().
inboxes()
template<typename Metavariables > template<typename Component > std::unordered_map<typename Component::index, tuples::TaggedTupleTypelist<Parallel::get_inbox_tags< typename Component::action_list> > >& ActionTesting::ActionRunner< Metavariables >::inboxes () inline noexcept
Access the inboxes for a given component.
is_ready()
template<typename Metavariables > template<typename Component , typename Action , typename DbTags > bool ActionTesting::ActionRunner< Metavariables >::is_ready (const db::DataBox< DbTags > & box, const typename Component::index & array_index) inline noexcept
Call Action::is_ready as if on the portion of Component labeled by array_index.
References cpp17::as_const().
nonempty_inboxes()
template<typename Metavariables > template<typename Component , typename InboxTag > std::unordered_set<typename Component::index> ActionTesting::ActionRunner< Metavariables >::nonempty_inboxes () inline noexcept
Find the set of array indices on Component where the specified inbox is not empty.
operator=() [1/2]
template<typename Metavariables > ActionRunner& ActionTesting::ActionRunner< Metavariables >::operator= (const ActionRunner< Metavariables > &) delete
operator=() [2/2]
template<typename Metavariables > ActionRunner& ActionTesting::ActionRunner< Metavariables >::operator= (ActionRunner< Metavariables > &&) delete
The documentation for this class was generated from the following file:
tests/Unit/ActionTesting.hpp