SpECTRE: CoordinateMaps::Affine Class Reference
CoordinateMaps::Affine Class Reference
Coordinate Maps
Affine map from \(\xi \in [A, B]\rightarrow x \in [a, b]\).
#include <Affine.hpp>
Public Member Functions
Affine (double A, double B, double a, double b)
Affine ()=default
~Affine ()=default
Affine (const Affine &)=default
Affine (Affine &&) noexcept=default
Affine & operator= (const Affine &)=default
Affine & operator= (Affine &&)=default
template<typename T >
std::array< tt::remove_cvref_wrap_t< T >, 1 > operator() (const std::array< T, 1 > &source_coords) const noexcept
template<typename T >
std::array< tt::remove_cvref_wrap_t< T >, 1 > inverse (const std::array< T, 1 > &target_coords) const noexcept
template<typename T >
tnsr::Ij< tt::remove_cvref_wrap_t< T >, 1, Frame::NoFrame > jacobian (const std::array< T, 1 > &source_coords) const noexcept
template<typename T >
tnsr::Ij< tt::remove_cvref_wrap_t< T >, 1, Frame::NoFrame > inv_jacobian (const std::array< T, 1 > &source_coords) const noexcept
void pup (PUP::er &p)
Static Public Attributes
static constexpr size_t dim = 1
Friends
bool operator== (const Affine &lhs, const Affine &rhs) noexcept
Detailed Description
Affine map from \(\xi \in [A, B]\rightarrow x \in [a, b]\).
The formula for the mapping is...
\[ x = \frac{b}{B-A} (\xi-A) +\frac{a}{B-A}(B-\xi) \]
\[ \xi =\frac{B}{b-a} (x-a) +\frac{A}{b-a}(b-x) \]
Constructor & Destructor Documentation
Affine() [1/4]
CoordinateMaps::Affine::Affine (double A, double B, double a, double b)
Affine() [2/4]
CoordinateMaps::Affine::Affine () default
~Affine()
CoordinateMaps::Affine::~Affine () default
Affine() [3/4]
CoordinateMaps::Affine::Affine (const Affine &) default
Affine() [4/4]
CoordinateMaps::Affine::Affine (Affine &&) default noexcept
Member Function Documentation
inv_jacobian()
template<typename T > tnsr::Ij< tt::remove_cvref_wrap_t< T >, 1, Frame::NoFrame > CoordinateMaps::Affine::inv_jacobian (const std::array< T, 1 > & source_coords) const noexcept
References dereference_wrapper(), and make_with_value().
inverse()
template<typename T > std::array< tt::remove_cvref_wrap_t< T >, 1 > CoordinateMaps::Affine::inverse (const std::array< T, 1 > & target_coords) const noexcept
jacobian()
template<typename T > tnsr::Ij< tt::remove_cvref_wrap_t< T >, 1, Frame::NoFrame > CoordinateMaps::Affine::jacobian (const std::array< T, 1 > & source_coords) const noexcept
References dereference_wrapper(), and make_with_value().
operator()()
template<typename T > std::array< tt::remove_cvref_wrap_t< T >, 1 > CoordinateMaps::Affine::operator() (const std::array< T, 1 > & source_coords) const noexcept
operator=() [1/2]
Affine& CoordinateMaps::Affine::operator= (const Affine &) default
operator=() [2/2]
Affine& CoordinateMaps::Affine::operator= (Affine &&) default
pup()
void CoordinateMaps::Affine::pup (PUP::er & p)
Friends And Related Function Documentation
operator==
bool operator== (const Affine & lhs, const Affine & rhs) friend
Member Data Documentation
dim
constexpr size_t CoordinateMaps::Affine::dim = 1 static
The documentation for this class was generated from the following files:
src/Domain/CoordinateMaps/Affine.hpp
src/Domain/CoordinateMaps/Affine.cpp