SpECTRE: FunctionsOfTime::PiecewisePolynomial< MaxDeriv > Class Template Reference
FunctionsOfTime::PiecewisePolynomial< MaxDeriv > Class Template Reference
Control System
A function that has a piecewise-constant MaxDerivth derivative.
#include <PiecewisePolynomial.hpp>
Public Member Functions
PiecewisePolynomial (double t, std::array< DataVector, MaxDeriv+1 > initial_func_and_derivs) noexcept
~PiecewisePolynomial () override=default
PiecewisePolynomial (PiecewisePolynomial &&) noexcept=default
PiecewisePolynomial & operator= (PiecewisePolynomial &&) noexcept=default
PiecewisePolynomial (const PiecewisePolynomial &)=delete
PiecewisePolynomial & operator= (const PiecewisePolynomial &)=delete
std::array< DataVector, 1 > func (double t) const noexcept override
Returns the function at an arbitrary time t.
std::array< DataVector, 2 > func_and_deriv (double t) const noexcept override
Returns the function and its first derivative at an arbitrary time t.
std::array< DataVector, 3 > func_and_2_derivs (double t) const noexcept override
Returns the function and the first two derivatives at an arbitrary time t.
void update (double time_of_update, DataVector updated_max_deriv) noexcept
Updates the MaxDerivth derivative of the function at the given time. updated_max_deriv is a vector of the MaxDerivths for each component.
std::array< double, 2 > time_bounds () const noexcept override
Returns the domain of validity of the function.
Public Member Functions inherited from FunctionOfTime
FunctionOfTime ()=default
FunctionOfTime (FunctionOfTime &&) noexcept=default
FunctionOfTime & operator= (FunctionOfTime &&) noexcept=default
FunctionOfTime (const FunctionOfTime &)=delete
FunctionOfTime & operator= (const FunctionOfTime &)=delete
virtual ~FunctionOfTime ()=default
Detailed Description
template<size_t MaxDeriv>
class FunctionsOfTime::PiecewisePolynomial< MaxDeriv >
A function that has a piecewise-constant MaxDerivth derivative.
Constructor & Destructor Documentation
PiecewisePolynomial() [1/3]
template<size_t MaxDeriv> FunctionsOfTime::PiecewisePolynomial< MaxDeriv >::PiecewisePolynomial (double t, std::array< DataVector, MaxDeriv+1 > initial_func_and_derivs) noexcept
References gsl::at().
~PiecewisePolynomial()
template<size_t MaxDeriv> FunctionsOfTime::PiecewisePolynomial< MaxDeriv >::~PiecewisePolynomial () override default
PiecewisePolynomial() [2/3]
template<size_t MaxDeriv> FunctionsOfTime::PiecewisePolynomial< MaxDeriv >::PiecewisePolynomial (PiecewisePolynomial< MaxDeriv > &&) default noexcept
PiecewisePolynomial() [3/3]
template<size_t MaxDeriv> FunctionsOfTime::PiecewisePolynomial< MaxDeriv >::PiecewisePolynomial (const PiecewisePolynomial< MaxDeriv > &) delete
Member Function Documentation
func()
template<size_t MaxDeriv> std::array<DataVector, 1> FunctionsOfTime::PiecewisePolynomial< MaxDeriv >::func (double t) const inline override virtual noexcept
Returns the function at an arbitrary time t.
Implements FunctionOfTime.
func_and_2_derivs()
template<size_t MaxDeriv> std::array<DataVector, 3> FunctionsOfTime::PiecewisePolynomial< MaxDeriv >::func_and_2_derivs (double t) const inline override virtual noexcept
Returns the function and the first two derivatives at an arbitrary time t.
Implements FunctionOfTime.
References FunctionsOfTime::PiecewisePolynomial< MaxDeriv >::update().
func_and_deriv()
template<size_t MaxDeriv> std::array<DataVector, 2> FunctionsOfTime::PiecewisePolynomial< MaxDeriv >::func_and_deriv (double t) const inline override virtual noexcept
Returns the function and its first derivative at an arbitrary time t.
Implements FunctionOfTime.
operator=() [1/2]
template<size_t MaxDeriv> PiecewisePolynomial& FunctionsOfTime::PiecewisePolynomial< MaxDeriv >::operator= (PiecewisePolynomial< MaxDeriv > &&) default noexcept
operator=() [2/2]
template<size_t MaxDeriv> PiecewisePolynomial& FunctionsOfTime::PiecewisePolynomial< MaxDeriv >::operator= (const PiecewisePolynomial< MaxDeriv > &) delete
time_bounds()
template<size_t MaxDeriv> std::array<double, 2> FunctionsOfTime::PiecewisePolynomial< MaxDeriv >::time_bounds () const inline override virtual noexcept
Returns the domain of validity of the function.
Implements FunctionOfTime.
update()
template<size_t MaxDeriv> void FunctionsOfTime::PiecewisePolynomial< MaxDeriv >::update (double time_of_update, DataVector updated_max_deriv) noexcept
Updates the MaxDerivth derivative of the function at the given time. updated_max_deriv is a vector of the MaxDerivths for each component.
References gsl::at(), equal_within_roundoff(), ERROR, and GENERATE_INSTANTIATIONS.
Referenced by FunctionsOfTime::PiecewisePolynomial< MaxDeriv >::func_and_2_derivs().
The documentation for this class was generated from the following files:
src/ControlSystem/PiecewisePolynomial.hpp
src/ControlSystem/PiecewisePolynomial.cpp