SpECTRE: DomainCreators::Sphere< TargetFrame > Class Template Reference
DomainCreators::Sphere< TargetFrame > Class Template Reference
Domain Creators
Create a 3D Domain in the shape of a sphere consisting of six wedges and a central cube.
#include <DomainCreator.hpp>
Classes
struct InitialGridPoints
struct InitialRefinement
struct InnerRadius
struct OuterRadius
struct UseEquiangularMap
Public Types
using options = tmpl::list< InnerRadius, OuterRadius, InitialRefinement, InitialGridPoints, UseEquiangularMap >
Public Types inherited from DomainCreator< 3, TargetFrame >
using creatable_classes = typename DomainCreators_detail::domain_creators< VolumeDim >::template creators< TargetFrame >
Public Member Functions
Sphere (typename InnerRadius::type inner_radius, typename OuterRadius::type outer_radius, typename InitialRefinement::type initial_refinement, typename InitialGridPoints::type initial_number_of_grid_points, typename UseEquiangularMap::type use_equiangular_map) noexcept
Sphere ()=default
Sphere (const Sphere &)=delete
Sphere (Sphere &&) noexcept=default
Sphere & operator= (const Sphere &)=delete
Sphere & operator= (Sphere &&) noexcept=default
~Sphere () noexcept override=default
Domain< 3, TargetFrame > create_domain () const noexcept override
std::vector< std::array< size_t, 3 > > initial_extents () const noexcept override
Obtain the initial grid extents of the block with the given index.
std::vector< std::array< size_t, 3 > > initial_refinement_levels () const noexcept override
Obtain the initial refinement levels of the blocks.
Public Member Functions inherited from DomainCreator< 3, TargetFrame >
DomainCreator ()=default
DomainCreator (const DomainCreator< VolumeDim, TargetFrame > &)=delete
DomainCreator (DomainCreator< VolumeDim, TargetFrame > &&) noexcept=default
DomainCreator< VolumeDim, TargetFrame > & operator= (const DomainCreator< VolumeDim, TargetFrame > &)=delete
DomainCreator< VolumeDim, TargetFrame > & operator= (DomainCreator< VolumeDim, TargetFrame > &&) noexcept=default
virtual ~DomainCreator ()=default
Static Public Attributes
static constexpr OptionString help
Detailed Description
template<typename TargetFrame>
class DomainCreators::Sphere< TargetFrame >
Create a 3D Domain in the shape of a sphere consisting of six wedges and a central cube.
Member Typedef Documentation
options
template<typename TargetFrame > using DomainCreators::Sphere< TargetFrame >::options = tmpl::list<InnerRadius, OuterRadius, InitialRefinement, InitialGridPoints, UseEquiangularMap>
Constructor & Destructor Documentation
Sphere() [1/4]
template<typename TargetFrame > DomainCreators::Sphere< TargetFrame >::Sphere (typename InnerRadius::type inner_radius, typename OuterRadius::type outer_radius, typename InitialRefinement::type initial_refinement, typename InitialGridPoints::type initial_number_of_grid_points, typename UseEquiangularMap::type use_equiangular_map) noexcept
Sphere() [2/4]
template<typename TargetFrame > DomainCreators::Sphere< TargetFrame >::Sphere () default
Sphere() [3/4]
template<typename TargetFrame > DomainCreators::Sphere< TargetFrame >::Sphere (const Sphere< TargetFrame > &) delete
Sphere() [4/4]
template<typename TargetFrame > DomainCreators::Sphere< TargetFrame >::Sphere (Sphere< TargetFrame > &&) default noexcept
~Sphere()
template<typename TargetFrame > DomainCreators::Sphere< TargetFrame >::~Sphere () override default noexcept
Member Function Documentation
create_domain()
template<typename TargetFrame > Domain< 3, TargetFrame > DomainCreators::Sphere< TargetFrame >::create_domain () const override virtual noexcept
Implements DomainCreator< 3, TargetFrame >.
References Direction< VolumeDim >::lower_eta(), Direction< VolumeDim >::lower_xi(), Direction< VolumeDim >::lower_zeta(), Direction< VolumeDim >::upper_eta(), Direction< VolumeDim >::upper_xi(), and Direction< VolumeDim >::upper_zeta().
initial_extents()
template<typename TargetFrame > std::vector< std::array< size_t, 3 > > DomainCreators::Sphere< TargetFrame >::initial_extents () const override virtual noexcept
Obtain the initial grid extents of the block with the given index.
Implements DomainCreator< 3, TargetFrame >.
initial_refinement_levels()
template<typename TargetFrame > std::vector< std::array< size_t, 3 > > DomainCreators::Sphere< TargetFrame >::initial_refinement_levels () const override virtual noexcept
Obtain the initial refinement levels of the blocks.
Implements DomainCreator< 3, TargetFrame >.
operator=() [1/2]
template<typename TargetFrame > Sphere& DomainCreators::Sphere< TargetFrame >::operator= (const Sphere< TargetFrame > &) delete
operator=() [2/2]
template<typename TargetFrame > Sphere& DomainCreators::Sphere< TargetFrame >::operator= (Sphere< TargetFrame > &&) default noexcept
Member Data Documentation
help
template<typename TargetFrame > constexpr OptionString DomainCreators::Sphere< TargetFrame >::help static
Initial value:
{
      "Creates a 3D Sphere with seven Blocks.\n"
      "Only one refinement level for all dimensions is currently supported.\n"
      "The number of gridpoints in the radial direction can be set\n"
      "independently of the number of gridpoints in the angular directions.\n"
      "The number of gridpoints along the dimensions of the cube is equal\n"
      "to the number of gridpoints along the angular dimensions of the "
      "wedges.\n"
      "Equiangular coordinates give better gridpoint spacings in the angular\n"
      "directions, while equidistant coordinates give better gridpoint\n"
      "spacings in the center block."}
The documentation for this class was generated from the following files:
src/Domain/DomainCreators/DomainCreator.hpp
src/Domain/DomainCreators/Sphere.hpp
src/Domain/DomainCreators/Sphere.cpp