SpECTRE: OrientationMap< VolumeDim > Class Template Reference
OrientationMap< VolumeDim > Class Template Reference
A mapping of the logical coordinate axes of a host to the logical coordinate axes of a neighbor of the host.
#include <OrientationMap.hpp>
Public Member Functions
OrientationMap ()
The default orientation is the identity map on directions. The bool is_aligned_ is correspondingly set to true.
OrientationMap (std::array< Direction< VolumeDim >, VolumeDim > mapped_directions)
OrientationMap (const std::array< Direction< VolumeDim >, VolumeDim > &directions_in_host, const std::array< Direction< VolumeDim >, VolumeDim > &directions_in_neighbor)
~OrientationMap ()=default
OrientationMap (const OrientationMap &)=default
OrientationMap & operator= (const OrientationMap &)=default
OrientationMap (OrientationMap &&) noexcept=default
OrientationMap & operator= (OrientationMap &&) noexcept=default
bool is_aligned () const noexcept
True when mapped(Direction) == Direction.
size_t operator() (const size_t dim) const noexcept
The corresponding dimension in the neighbor.
Direction< VolumeDim > operator() (const Direction< VolumeDim > &direction) const
The corresponding direction in the neighbor.
std::array< SegmentId, VolumeDim > operator() (const std::array< SegmentId, VolumeDim > &segmentIds) const
The corresponding SegmentIds in the neighbor.
OrientationMap< VolumeDim > inverse_map () const noexcept
The corresponding Orientation of the host in the frame of the neighbor.
void pup (PUP::er &p)
Serialization for Charm++.
Friends
bool operator== (const OrientationMap &lhs, const OrientationMap &rhs) noexcept
Detailed Description
template<size_t VolumeDim>
class OrientationMap< VolumeDim >
A mapping of the logical coordinate axes of a host to the logical coordinate axes of a neighbor of the host.
Usage
Given a size_t dimension, a Direction, or a SegmentId of the host, an OrientationMap will give the corresponding value in the neighbor.
Template Parameters
VolumeDim the dimension of the blocks.
Constructor & Destructor Documentation
OrientationMap() [1/5]
template<size_t VolumeDim> OrientationMap< VolumeDim >::OrientationMap ()
The default orientation is the identity map on directions. The bool is_aligned_ is correspondingly set to true.
References gsl::at(), and Upper.
OrientationMap() [2/5]
template<size_t VolumeDim> OrientationMap< VolumeDim >::OrientationMap (std::array< Direction< VolumeDim >, VolumeDim > mapped_directions) explicit
References gsl::at(), and Upper.
OrientationMap() [3/5]
template<size_t VolumeDim> OrientationMap< VolumeDim >::OrientationMap (const std::array< Direction< VolumeDim >, VolumeDim > & directions_in_host, const std::array< Direction< VolumeDim >, VolumeDim > & directions_in_neighbor)
References gsl::at(), and Upper.
~OrientationMap()
template<size_t VolumeDim> OrientationMap< VolumeDim >::~OrientationMap () default
OrientationMap() [4/5]
template<size_t VolumeDim> OrientationMap< VolumeDim >::OrientationMap (const OrientationMap< VolumeDim > &) default
OrientationMap() [5/5]
template<size_t VolumeDim> OrientationMap< VolumeDim >::OrientationMap (OrientationMap< VolumeDim > &&) default noexcept
Member Function Documentation
inverse_map()
template<size_t VolumeDim> OrientationMap< VolumeDim > OrientationMap< VolumeDim >::inverse_map () const noexcept
The corresponding Orientation of the host in the frame of the neighbor.
References gsl::at().
Referenced by OrientationMap< VolumeDim >::operator()().
is_aligned()
template<size_t VolumeDim> bool OrientationMap< VolumeDim >::is_aligned () const inline noexcept
True when mapped(Direction) == Direction.
operator()() [1/3]
template<size_t VolumeDim> size_t OrientationMap< VolumeDim >::operator() (const size_t dim) const inline noexcept
The corresponding dimension in the neighbor.
References gsl::at().
Referenced by OrientationMap< VolumeDim >::operator()().
operator()() [2/3]
template<size_t VolumeDim> Direction<VolumeDim> OrientationMap< VolumeDim >::operator() (const Direction< VolumeDim > & direction) const inline
The corresponding direction in the neighbor.
References gsl::at(), Direction< VolumeDim >::dimension(), OrientationMap< VolumeDim >::inverse_map(), OrientationMap< VolumeDim >::operator()(), opposite(), OrientationMap< VolumeDim >::pup(), Direction< VolumeDim >::side(), and Upper.
operator()() [3/3]
template<size_t VolumeDim> std::array< SegmentId, VolumeDim > OrientationMap< VolumeDim >::operator() (const std::array< SegmentId, VolumeDim > & segmentIds) const
The corresponding SegmentIds in the neighbor.
References gsl::at(), and Upper.
operator=() [1/2]
template<size_t VolumeDim> OrientationMap& OrientationMap< VolumeDim >::operator= (const OrientationMap< VolumeDim > &) default
operator=() [2/2]
template<size_t VolumeDim> OrientationMap& OrientationMap< VolumeDim >::operator= (OrientationMap< VolumeDim > &&) default noexcept
pup()
template<size_t VolumeDim> void OrientationMap< VolumeDim >::pup (PUP::er & p)
Serialization for Charm++.
Referenced by OrientationMap< VolumeDim >::operator()().
Friends And Related Function Documentation
operator==
template<size_t VolumeDim> bool operator== (const OrientationMap< VolumeDim > & lhs, const OrientationMap< VolumeDim > & rhs) friend
The documentation for this class was generated from the following files:
src/Domain/OrientationMap.hpp
src/Domain/OrientationMap.cpp