SpECTRE: CoordinateMaps::Wedge3D Class Reference
CoordinateMaps::Wedge3D Class Reference
Coordinate Maps
Three dimensional map from the cube to a wedge.
#include <Wedge3D.hpp>
Public Member Functions
Wedge3D (double radius_of_other_surface, double radius_of_spherical_surface, Direction< 3 > direction_of_wedge, double sphericity_of_other_surface, bool with_equiangular_map) noexcept
Wedge3D ()=default
~Wedge3D ()=default
Wedge3D (Wedge3D &&)=default
Wedge3D (const Wedge3D &)=default
Wedge3D & operator= (const Wedge3D &)=default
Wedge3D & operator= (Wedge3D &&)=default
template<typename T >
std::array< tt::remove_cvref_wrap_t< T >, 3 > operator() (const std::array< T, 3 > &source_coords) const noexcept
template<typename T >
std::array< tt::remove_cvref_wrap_t< T >, 3 > inverse (const std::array< T, 3 > &target_coords) const noexcept
template<typename T >
tnsr::Ij< tt::remove_cvref_wrap_t< T >, 3, Frame::NoFrame > jacobian (const std::array< T, 3 > &source_coords) const noexcept
template<typename T >
tnsr::Ij< tt::remove_cvref_wrap_t< T >, 3, Frame::NoFrame > inv_jacobian (const std::array< T, 3 > &source_coords) const noexcept
void pup (PUP::er &p) noexcept
Static Public Attributes
static constexpr size_t dim = 3
Friends
bool operator== (const Wedge3D &lhs, const Wedge3D &rhs) noexcept
Detailed Description
Three dimensional map from the cube to a wedge.
Details
The mapping that goes from a reference cube to a three-dimensional wedge centered on a coordinate axis covering a volume between an inner surface and outer surface. One of the surfaces must be spherical, but the curvature of the other surface can be anything between flat (a sphericity of 0) and spherical (a sphericity of 1).
The first two logical coordinates correspond to the two angular coordinates, and the third to the radial coordinate.
The Wedge3D map is constructed by linearly interpolating between a bulged face of radius radius_of_other_surface to a spherical face of radius radius_of_spherical_surface, where the radius of the bulged face is defined to be the radius of the sphere circumscribing the bulge.
We make a choice here as to whether we wish to use the logical coordinates parameterizing these surface as they are, in which case we have the equidistant choice of coordinates, or whether to apply a tangent map to them which leads us to the equiangular choice of coordinates. In terms of the logical coordinates, the equiangular coordinates are:
\[\textrm{equiangular xi} : \Xi(\xi) = \textrm{tan}(\xi\pi/4)\]
\[\textrm{equiangular eta} : \mathrm{H}(\eta) = \textrm{tan}(\eta\pi/4)\]
With derivatives:
\[\Xi'(\xi) = \frac{\pi}{4}(1+\Xi^2)\]
\[\mathrm{H}'(\eta) = \frac{\pi}{4}(1+\mathrm{H}^2)\]
The equidistant coordinates are:
\[ \textrm{equidistant xi} : \Xi = \xi\]
\[ \textrm{equidistant eta} : \mathrm{H} = \eta\]
with derivatives:
\(\Xi'(\xi) = 1\), and \(\mathrm{H}'(\eta) = 1\)
We also define the variable \(\rho\), given by:
\[\textrm{rho} : \rho = \sqrt{1+\Xi^2+\mathrm{H}^2}\]
The Spherical Face Map
The surface map for the spherical face of radius \(R\) lying in the \(+z\) direction in either choice of coordinates is then given by:
\[\sigma_{spherical}: \vec{\xi} \rightarrow \vec{x}(\vec{\xi})\]
Where
\[ \vec{x}(\xi,\eta) = \begin{bmatrix} x(\xi,\eta)\\ y(\xi,\eta)\\ z(\xi,\eta)\\ \end{bmatrix} = R \begin{bmatrix} \Xi/\rho\\ \mathrm{H}/\rho\\ 1/\rho\\ \end{bmatrix}\]
The Bulged Face Map
The bulged surface is itself constructed by linearly interpolating between a cubical face and a spherical face. The surface map for the cubical face of side length \(2L\) lying in the \(+z\) direction is given by:
\[\vec{\sigma}_{cubical}: \vec{\xi} \rightarrow \vec{x}(\vec{\xi})\]
Where
\[ \vec{x}(\xi,\eta) = \begin{bmatrix} x(\xi,\eta)\\ y(\xi,\eta)\\ L\\ \end{bmatrix} = L \begin{bmatrix} \Xi\\ \mathrm{H}\\ 1\\ \end{bmatrix}\]
To construct the bulged map we interpolate between this cubical face map and a spherical face map of radius radius_of_other_surface, with the interpolation parameter being \(s\), the sphericity_of_other_surface. The surface map for the bulged face lying in the \(+z\) direction is then given by:
\[\vec{\sigma}_{other}(\xi,\eta) = {(1-s)L + \frac{sR_{other}}{\rho}} \begin{bmatrix} \Xi\\ \mathrm{H}\\ 1\\ \end{bmatrix}\]
We constrain L by demanding that the spherical face circumscribe the cube. With this condition, we have \(L = R_{other}/\sqrt3\).
The Full Volume Map
The final map for the wedge which lies along the \(+z\) is obtained by interpolating between the spherical and bulged surfaces with the interpolation parameter being the logical coordinate \(\zeta\). This results in:
\[\vec{x}(\xi,\eta,\zeta) = \frac{1}{2}\big\{(1-\zeta)(1-s)L + (1-\zeta)s\frac{R_{other}}{\rho} + (1+\zeta)\frac{R_{spherical}}{\rho}\big\}\begin{bmatrix} \Xi\\ \mathrm{H}\\ 1\\ \end{bmatrix}\]
We will define the variables \(b_{f1}\) and \(b_{f2}\), the first and second blending factors:
\[b_{f1} = \frac{1}{2}\big\{(1-\zeta)(1-s)L\big\}\]
\[b_{f2} = \frac{1}{2}\big\{(1-\zeta)sR_{other} + (1+\zeta)R_{spherical} \big\}\]
We also define their zeta-derivatives, the blending rates:
\[b_{r1} = \frac{\mathrm{d}b_{f1}}{\mathrm{d}\zeta} = \frac{1}{2}(s-1)L\]
\[b_{r2} = \frac{\mathrm{d}b_{f2}}{\mathrm{d}\zeta} = \frac{1}{2}\big\{-sR_{other} + R_{spherical}\big\}\]
The Jacobian then is:
\[J = \begin{bmatrix} b_{f1}\Xi' & 0 &b_{r1}\Xi\\ 0 & b_{f1}\mathrm{H}' &b_{r1}\mathrm{H}\\ 0 & 0 &b_{r1}\\ \end{bmatrix} + \begin{bmatrix} b_{f2}\Xi'(1+\mathrm{H}^2)/{\rho^3} & -b_{f2}\mathrm{H}'\Xi\mathrm{H}/\rho^3 & b_{r2}\Xi/\rho\\ -b_{f2}\Xi'\Xi\mathrm{H}/\rho^3 & b_{f2}\mathrm{H}'(1+\Xi^2)/\rho^3 & b_{r2}\mathrm{H}/\rho\\ -b_{f2}\Xi'\Xi/\rho^3 & -b_{f2}\mathrm{H}'\mathrm{H}/\rho^3 & b_{r2}/\rho\\ \end{bmatrix} \]
Note
This differs from the choice in SpEC where it is demanded that the surfaces touch at the center, which leads to \(L = R_{other}\).
Constructor & Destructor Documentation
Wedge3D() [1/4]
CoordinateMaps::Wedge3D::Wedge3D (double radius_of_other_surface, double radius_of_spherical_surface, Direction< 3 > direction_of_wedge, double sphericity_of_other_surface, bool with_equiangular_map) noexcept
Constructs a 3D wedge.
Parameters
radius_of_spherical_surface Radius of the spherical surface
radius_of_other_surface Distance from the origin to one of the corners which lie on the other surface, which may be anything between flat and spherical.
direction_of_wedge The axis on which the wedge is centred.
sphericity_of_other_surface Value between 0 and 1 which determines whether the other surface is flat (value of 0), spherical (value of 1) or somewhere in between
with_equiangular_map Determines whether to apply a tangent function mapping to the logical coordinates (for 'true') or not (for 'false').
References ASSERT.
Wedge3D() [2/4]
CoordinateMaps::Wedge3D::Wedge3D () default
~Wedge3D()
CoordinateMaps::Wedge3D::~Wedge3D () default
Wedge3D() [3/4]
CoordinateMaps::Wedge3D::Wedge3D (Wedge3D &&) default
Wedge3D() [4/4]
CoordinateMaps::Wedge3D::Wedge3D (const Wedge3D &) default
Member Function Documentation
inv_jacobian()
template<typename T > tnsr::Ij< tt::remove_cvref_wrap_t< T >, 3, Frame::NoFrame > CoordinateMaps::Wedge3D::inv_jacobian (const std::array< T, 3 > & source_coords) const noexcept
References determinant_and_inverse().
inverse()
template<typename T > std::array< tt::remove_cvref_wrap_t< T >, 3 > CoordinateMaps::Wedge3D::inverse (const std::array< T, 3 > & target_coords) const noexcept
References ERROR, square(), and Upper.
jacobian()
template<typename T > tnsr::Ij< tt::remove_cvref_wrap_t< T >, 3, Frame::NoFrame > CoordinateMaps::Wedge3D::jacobian (const std::array< T, 3 > & source_coords) const noexcept
References dereference_wrapper(), and square().
operator()()
template<typename T > std::array< tt::remove_cvref_wrap_t< T >, 3 > CoordinateMaps::Wedge3D::operator() (const std::array< T, 3 > & source_coords) const noexcept
References ERROR, square(), and Upper.
operator=() [1/2]
Wedge3D& CoordinateMaps::Wedge3D::operator= (const Wedge3D &) default
operator=() [2/2]
Wedge3D& CoordinateMaps::Wedge3D::operator= (Wedge3D &&) default
pup()
void CoordinateMaps::Wedge3D::pup (PUP::er & p) noexcept
Friends And Related Function Documentation
operator==
bool operator== (const Wedge3D & lhs, const Wedge3D & rhs) friend
Member Data Documentation
dim
constexpr size_t CoordinateMaps::Wedge3D::dim = 3 static
The documentation for this class was generated from the following files:
src/Domain/CoordinateMaps/Wedge3D.hpp
src/Domain/CoordinateMaps/Wedge3D.cpp