SpECTRE: TimeSteppers::BoundaryHistory< LocalVars, RemoteVars, CouplingResult > Class Template Reference
TimeSteppers::BoundaryHistory< LocalVars, RemoteVars, CouplingResult > Class Template Reference
Time Steppers
History data used by a TimeStepper for boundary integration.
#include <BoundaryHistory.hpp>
Public Types
using local_iterator = IteratorType< LocalVars >
using remote_iterator = IteratorType< RemoteVars >
Public Member Functions
BoundaryHistory ()=default
BoundaryHistory (const BoundaryHistory &)=delete
BoundaryHistory (BoundaryHistory &&)=default
BoundaryHistory & operator= (const BoundaryHistory &)=delete
BoundaryHistory & operator= (BoundaryHistory &&)=default
~BoundaryHistory ()=default
template<typename Coupling >
const CouplingResult & coupling (Coupling &&c, const local_iterator &local, const remote_iterator &remote) noexcept
Evaluate the coupling function at the given local and remote history entries. The coupling function will be passed the local and remote FluxVars and should return a CouplingResult. Values are cached internally, so callers should ensure that the coupling functions provided on separate calls produce the same result.
void pup (PUP::er &p) noexcept
void local_insert (Time time, LocalVars vars) noexcept
Add a new value to the end of the history of the indicated side.
void remote_insert (Time time, RemoteVars vars) noexcept
Add a new value to the end of the history of the indicated side.
void local_insert_initial (Time time, LocalVars vars) noexcept
Add a new value to the front of the history of the indicated side. This is often convenient for setting initial data.
void remote_insert_initial (Time time, RemoteVars vars) noexcept
Add a new value to the front of the history of the indicated side. This is often convenient for setting initial data.
void local_mark_unneeded (const local_iterator &first_needed) noexcept
Mark all data before the passed point in history on the indicated side as unneeded so it can be removed. Calling this directly should not often be necessary, as it is handled internally by the time steppers.
void remote_mark_unneeded (const remote_iterator &first_needed) noexcept
Mark all data before the passed point in history on the indicated side as unneeded so it can be removed. Calling this directly should not often be necessary, as it is handled internally by the time steppers.
local_iterator local_begin () const noexcept
Access to the sequence of times on the indicated side.
local_iterator local_end () const noexcept
Access to the sequence of times on the indicated side.
remote_iterator remote_begin () const noexcept
Access to the sequence of times on the indicated side.
remote_iterator remote_end () const noexcept
Access to the sequence of times on the indicated side.
size_t local_size () const noexcept
Access to the sequence of times on the indicated side.
size_t remote_size () const noexcept
Access to the sequence of times on the indicated side.
Detailed Description
template<typename LocalVars, typename RemoteVars, typename CouplingResult>
class TimeSteppers::BoundaryHistory< LocalVars, RemoteVars, CouplingResult >
History data used by a TimeStepper for boundary integration.
Template Parameters
LocalVars local variables passed to the boundary coupling
RemoteVars remote variables passed to the boundary coupling
CouplingResult result of the coupling function
Member Typedef Documentation
local_iterator
template<typename LocalVars , typename RemoteVars , typename CouplingResult > using TimeSteppers::BoundaryHistory< LocalVars, RemoteVars, CouplingResult >::local_iterator = IteratorType<LocalVars>
remote_iterator
template<typename LocalVars , typename RemoteVars , typename CouplingResult > using TimeSteppers::BoundaryHistory< LocalVars, RemoteVars, CouplingResult >::remote_iterator = IteratorType<RemoteVars>
Constructor & Destructor Documentation
BoundaryHistory() [1/3]
template<typename LocalVars , typename RemoteVars , typename CouplingResult > TimeSteppers::BoundaryHistory< LocalVars, RemoteVars, CouplingResult >::BoundaryHistory () default
BoundaryHistory() [2/3]
template<typename LocalVars , typename RemoteVars , typename CouplingResult > TimeSteppers::BoundaryHistory< LocalVars, RemoteVars, CouplingResult >::BoundaryHistory (const BoundaryHistory< LocalVars, RemoteVars, CouplingResult > &) delete
BoundaryHistory() [3/3]
template<typename LocalVars , typename RemoteVars , typename CouplingResult > TimeSteppers::BoundaryHistory< LocalVars, RemoteVars, CouplingResult >::BoundaryHistory (BoundaryHistory< LocalVars, RemoteVars, CouplingResult > &&) default
~BoundaryHistory()
template<typename LocalVars , typename RemoteVars , typename CouplingResult > TimeSteppers::BoundaryHistory< LocalVars, RemoteVars, CouplingResult >::~BoundaryHistory () default
Member Function Documentation
coupling()
template<typename LocalVars , typename RemoteVars , typename CouplingResult > template<typename Coupling > const CouplingResult & TimeSteppers::BoundaryHistory< LocalVars, RemoteVars, CouplingResult >::coupling (Coupling && c, const local_iterator & local, const remote_iterator & remote) noexcept
Evaluate the coupling function at the given local and remote history entries. The coupling function will be passed the local and remote FluxVars and should return a CouplingResult. Values are cached internally, so callers should ensure that the coupling functions provided on separate calls produce the same result.
References cpp17::as_const().
Referenced by TimeSteppers::BoundaryHistory< LocalVars, RemoteVars, CouplingResult >::remote_size().
local_begin()
template<typename LocalVars , typename RemoteVars , typename CouplingResult > local_iterator TimeSteppers::BoundaryHistory< LocalVars, RemoteVars, CouplingResult >::local_begin () const inline noexcept
Access to the sequence of times on the indicated side.
local_end()
template<typename LocalVars , typename RemoteVars , typename CouplingResult > local_iterator TimeSteppers::BoundaryHistory< LocalVars, RemoteVars, CouplingResult >::local_end () const inline noexcept
Access to the sequence of times on the indicated side.
local_insert()
template<typename LocalVars , typename RemoteVars , typename CouplingResult > void TimeSteppers::BoundaryHistory< LocalVars, RemoteVars, CouplingResult >::local_insert (Time time, LocalVars vars) inline noexcept
Add a new value to the end of the history of the indicated side.
local_insert_initial()
template<typename LocalVars , typename RemoteVars , typename CouplingResult > void TimeSteppers::BoundaryHistory< LocalVars, RemoteVars, CouplingResult >::local_insert_initial (Time time, LocalVars vars) inline noexcept
Add a new value to the front of the history of the indicated side. This is often convenient for setting initial data.
local_mark_unneeded()
template<typename LocalVars , typename RemoteVars , typename CouplingResult > void TimeSteppers::BoundaryHistory< LocalVars, RemoteVars, CouplingResult >::local_mark_unneeded (const local_iterator & first_needed) inline noexcept
Mark all data before the passed point in history on the indicated side as unneeded so it can be removed. Calling this directly should not often be necessary, as it is handled internally by the time steppers.
References make_not_null().
local_size()
template<typename LocalVars , typename RemoteVars , typename CouplingResult > size_t TimeSteppers::BoundaryHistory< LocalVars, RemoteVars, CouplingResult >::local_size () const inline noexcept
Access to the sequence of times on the indicated side.
operator=() [1/2]
template<typename LocalVars , typename RemoteVars , typename CouplingResult > BoundaryHistory& TimeSteppers::BoundaryHistory< LocalVars, RemoteVars, CouplingResult >::operator= (const BoundaryHistory< LocalVars, RemoteVars, CouplingResult > &) delete
operator=() [2/2]
template<typename LocalVars , typename RemoteVars , typename CouplingResult > BoundaryHistory& TimeSteppers::BoundaryHistory< LocalVars, RemoteVars, CouplingResult >::operator= (BoundaryHistory< LocalVars, RemoteVars, CouplingResult > &&) default
pup()
template<typename LocalVars , typename RemoteVars , typename CouplingResult > void TimeSteppers::BoundaryHistory< LocalVars, RemoteVars, CouplingResult >::pup (PUP::er & p) noexcept
References ASSERT.
Referenced by TimeSteppers::BoundaryHistory< LocalVars, RemoteVars, CouplingResult >::remote_size().
remote_begin()
template<typename LocalVars , typename RemoteVars , typename CouplingResult > remote_iterator TimeSteppers::BoundaryHistory< LocalVars, RemoteVars, CouplingResult >::remote_begin () const inline noexcept
Access to the sequence of times on the indicated side.
remote_end()
template<typename LocalVars , typename RemoteVars , typename CouplingResult > remote_iterator TimeSteppers::BoundaryHistory< LocalVars, RemoteVars, CouplingResult >::remote_end () const inline noexcept
Access to the sequence of times on the indicated side.
remote_insert()
template<typename LocalVars , typename RemoteVars , typename CouplingResult > void TimeSteppers::BoundaryHistory< LocalVars, RemoteVars, CouplingResult >::remote_insert (Time time, RemoteVars vars) inline noexcept
Add a new value to the end of the history of the indicated side.
remote_insert_initial()
template<typename LocalVars , typename RemoteVars , typename CouplingResult > void TimeSteppers::BoundaryHistory< LocalVars, RemoteVars, CouplingResult >::remote_insert_initial (Time time, RemoteVars vars) inline noexcept
Add a new value to the front of the history of the indicated side. This is often convenient for setting initial data.
remote_mark_unneeded()
template<typename LocalVars , typename RemoteVars , typename CouplingResult > void TimeSteppers::BoundaryHistory< LocalVars, RemoteVars, CouplingResult >::remote_mark_unneeded (const remote_iterator & first_needed) inline noexcept
Mark all data before the passed point in history on the indicated side as unneeded so it can be removed. Calling this directly should not often be necessary, as it is handled internally by the time steppers.
References make_not_null().
remote_size()
template<typename LocalVars , typename RemoteVars , typename CouplingResult > size_t TimeSteppers::BoundaryHistory< LocalVars, RemoteVars, CouplingResult >::remote_size () const inline noexcept
Access to the sequence of times on the indicated side.
References TimeSteppers::BoundaryHistory< LocalVars, RemoteVars, CouplingResult >::coupling(), and TimeSteppers::BoundaryHistory< LocalVars, RemoteVars, CouplingResult >::pup().
The documentation for this class was generated from the following file:
src/Time/BoundaryHistory.hpp