SpECTRE: DomainCreators::Disk< TargetFrame > Class Template Reference
DomainCreators::Disk< TargetFrame > Class Template Reference
Domain Creators
Create a 2D Domain in the shape of a disk from a square surrounded by four wedges.
#include <Disk.hpp>
Classes
struct InitialGridPoints
struct InitialRefinement
struct InnerRadius
struct OuterRadius
struct UseEquiangularMap
Public Types
using options = tmpl::list< InnerRadius, OuterRadius, InitialRefinement, InitialGridPoints, UseEquiangularMap >
Public Types inherited from DomainCreator< 2, TargetFrame >
using creatable_classes = typename DomainCreators_detail::domain_creators< VolumeDim >::template creators< TargetFrame >
Public Member Functions
Disk (typename InnerRadius::type inner_radius, typename OuterRadius::type outer_radius, typename InitialRefinement::type initial_refinement, typename InitialGridPoints::type initial_number_of_grid_points, typename UseEquiangularMap::type use_equiangular_map) noexcept
Disk ()=default
Disk (const Disk &)=delete
Disk (Disk &&) noexcept=default
Disk & operator= (const Disk &)=delete
Disk & operator= (Disk &&) noexcept=default
~Disk () noexcept override=default
Domain< 2, TargetFrame > create_domain () const noexcept override
std::vector< std::array< size_t, 2 > > initial_extents () const noexcept override
Obtain the initial grid extents of the block with the given index.
std::vector< std::array< size_t, 2 > > initial_refinement_levels () const noexcept override
Obtain the initial refinement levels of the blocks.
Public Member Functions inherited from DomainCreator< 2, TargetFrame >
DomainCreator ()=default
DomainCreator (const DomainCreator< VolumeDim, TargetFrame > &)=delete
DomainCreator (DomainCreator< VolumeDim, TargetFrame > &&) noexcept=default
DomainCreator< VolumeDim, TargetFrame > & operator= (const DomainCreator< VolumeDim, TargetFrame > &)=delete
DomainCreator< VolumeDim, TargetFrame > & operator= (DomainCreator< VolumeDim, TargetFrame > &&) noexcept=default
virtual ~DomainCreator ()=default
Static Public Attributes
static constexpr OptionString help
Detailed Description
template<typename TargetFrame>
class DomainCreators::Disk< TargetFrame >
Create a 2D Domain in the shape of a disk from a square surrounded by four wedges.
Member Typedef Documentation
options
template<typename TargetFrame > using DomainCreators::Disk< TargetFrame >::options = tmpl::list<InnerRadius, OuterRadius, InitialRefinement, InitialGridPoints, UseEquiangularMap>
Constructor & Destructor Documentation
Disk() [1/4]
template<typename TargetFrame > DomainCreators::Disk< TargetFrame >::Disk (typename InnerRadius::type inner_radius, typename OuterRadius::type outer_radius, typename InitialRefinement::type initial_refinement, typename InitialGridPoints::type initial_number_of_grid_points, typename UseEquiangularMap::type use_equiangular_map) noexcept
Disk() [2/4]
template<typename TargetFrame > DomainCreators::Disk< TargetFrame >::Disk () default
Disk() [3/4]
template<typename TargetFrame > DomainCreators::Disk< TargetFrame >::Disk (const Disk< TargetFrame > &) delete
Disk() [4/4]
template<typename TargetFrame > DomainCreators::Disk< TargetFrame >::Disk (Disk< TargetFrame > &&) default noexcept
~Disk()
template<typename TargetFrame > DomainCreators::Disk< TargetFrame >::~Disk () override default noexcept
Member Function Documentation
create_domain()
template<typename TargetFrame > Domain< 2, TargetFrame > DomainCreators::Disk< TargetFrame >::create_domain () const override virtual noexcept
Implements DomainCreator< 2, TargetFrame >.
References Direction< VolumeDim >::lower_eta(), Direction< VolumeDim >::lower_xi(), Direction< VolumeDim >::upper_eta(), and Direction< VolumeDim >::upper_xi().
initial_extents()
template<typename TargetFrame > std::vector< std::array< size_t, 2 > > DomainCreators::Disk< TargetFrame >::initial_extents () const override virtual noexcept
Obtain the initial grid extents of the block with the given index.
Implements DomainCreator< 2, TargetFrame >.
initial_refinement_levels()
template<typename TargetFrame > std::vector< std::array< size_t, 2 > > DomainCreators::Disk< TargetFrame >::initial_refinement_levels () const override virtual noexcept
Obtain the initial refinement levels of the blocks.
Implements DomainCreator< 2, TargetFrame >.
operator=() [1/2]
template<typename TargetFrame > Disk& DomainCreators::Disk< TargetFrame >::operator= (const Disk< TargetFrame > &) delete
operator=() [2/2]
template<typename TargetFrame > Disk& DomainCreators::Disk< TargetFrame >::operator= (Disk< TargetFrame > &&) default noexcept
Member Data Documentation
help
template<typename TargetFrame > constexpr OptionString DomainCreators::Disk< TargetFrame >::help static
Initial value:
{
      "Creates a 2D Disk with five Blocks.\n"
      "Only one refinement level for both dimensions is currently supported.\n"
      "The number of gridpoints in each dimension can be set independently.\n"
      "The number of gridpoints along the dimensions of the square is equal\n"
      "to the number of gridpoints along the angular dimension of the wedges.\n"
      "Equiangular coordinates give better gridpoint spacings in the angular\n"
      "direction, while equidistant coordinates give better gridpoint\n"
      "spacings in the center block."}
The documentation for this class was generated from the following files:
src/Domain/DomainCreators/Disk.hpp
src/Domain/DomainCreators/Disk.cpp