SpECTRE: src/ApparentHorizons/FastFlow.hpp File Reference
FastFlow.hpp File Reference
#include <cstddef>
#include <limits>
#include <memory>
#include <ostream>
#include "DataStructures/Tensor/TypeAliases.hpp"
#include "Options/Options.hpp"
#include "Utilities/ForceInline.hpp"
#include "Utilities/Gsl.hpp"
Classes
class Strahlkorper< Frame >
A star-shaped surface expanded in spherical harmonics.
class FastFlow
Fast flow method for finding apparent horizons.
struct FastFlow::IterInfo
Holds information about an iteration of the algorithm.
struct FastFlow::Flow
struct FastFlow::Alpha
struct FastFlow::Beta
struct FastFlow::AbsTol
struct FastFlow::TruncationTol
struct FastFlow::DivergenceTol
struct FastFlow::DivergenceIter
struct FastFlow::MaxIts
struct create_from_yaml< FastFlow::FlowType >
Functions
bool converged (const FastFlow::Status &status) noexcept
std::ostream & operator<< (std::ostream &os, const FastFlow::FlowType &flow_type) noexcept
std::ostream & operator<< (std::ostream &os, const FastFlow::Status &status) noexcept
bool operator!= (const FastFlow &lhs, const FastFlow &rhs) noexcept
Function Documentation
converged()
bool converged (const FastFlow::Status & status) noexcept
References operator<<().
operator!=()
bool operator!= (const FastFlow & lhs, const FastFlow & rhs) noexcept
Referenced by operator<<().
operator<<() [1/2]
std::ostream& operator<< (std::ostream & os, const FastFlow::FlowType & flow_type) noexcept
References FastFlow::Curvature, ERROR, FastFlow::Fast, and FastFlow::Jacobi.
Referenced by converged().
operator<<() [2/2]
std::ostream& operator<< (std::ostream & os, const FastFlow::Status & status) noexcept
References FastFlow::AbsTol, FastFlow::DivergenceError, ERROR, FastFlow::MaxIts, FastFlow::NegativeRadius, FastFlow::SuccessfulIteration, and FastFlow::TruncationTol.