SpECTRE: src/ApparentHorizons/FastFlow.cpp File Reference
FastFlow.cpp File Reference
#include "ApparentHorizons/FastFlow.hpp"
#include <algorithm>
#include <cmath>
#include <pup.h>
#include <utility>
#include "ApparentHorizons/SpherepackIterator.hpp"
#include "ApparentHorizons/Strahlkorper.hpp"
#include "ApparentHorizons/StrahlkorperDataBox.hpp"
#include "ApparentHorizons/StrahlkorperGr.hpp"
#include "ApparentHorizons/YlmSpherepack.hpp"
#include "DataStructures/DataBox/DataBox.hpp"
#include "DataStructures/DataVector.hpp"
#include "DataStructures/Tensor/EagerMath/Magnitude.hpp"
#include "ErrorHandling/Error.hpp"
#include "Options/ParseOptions.hpp"
#include "Parallel/Abort.hpp"
#include "PointwiseFunctions/GeneralRelativity/IndexManipulation.hpp"
#include "Utilities/EqualWithinRoundoff.hpp"
Functions
std::ostream & operator<< (std::ostream &os, const FastFlow::FlowType &flow_type) noexcept
std::ostream & operator<< (std::ostream &os, const FastFlow::Status &status) noexcept
bool operator== (const FastFlow &lhs, const FastFlow &rhs) noexcept
template std::pair< FastFlow::Status, FastFlow::IterInfo > FastFlow::iterate_horizon_finder< Frame::Inertial > (const gsl::not_null< Strahlkorper< Frame::Inertial > *> current_strahlkorper, const tnsr::II< DataVector, 3, Frame::Inertial > &upper_spatial_metric, const tnsr::ii< DataVector, 3, Frame::Inertial > &extrinsic_curvature, const tnsr::Ijj< DataVector, 3, Frame::Inertial > &christoffel_2nd_kind) noexcept
Function Documentation
FastFlow::iterate_horizon_finder< Frame::Inertial >()
template std::pair<FastFlow::Status, FastFlow::IterInfo> FastFlow::iterate_horizon_finder< Frame::Inertial > (const gsl::not_null< Strahlkorper< Frame::Inertial > *> current_strahlkorper, const tnsr::II< DataVector, 3, Frame::Inertial > & upper_spatial_metric, const tnsr::ii< DataVector, 3, Frame::Inertial > & extrinsic_curvature, const tnsr::Ijj< DataVector, 3, Frame::Inertial > & christoffel_2nd_kind) noexcept
operator<<() [1/2]
std::ostream& operator<< (std::ostream & os, const FastFlow::FlowType & flow_type) noexcept
References FastFlow::Curvature, ERROR, FastFlow::Fast, and FastFlow::Jacobi.
Referenced by converged().
operator<<() [2/2]
std::ostream& operator<< (std::ostream & os, const FastFlow::Status & status) noexcept
References FastFlow::AbsTol, FastFlow::DivergenceError, ERROR, FastFlow::MaxIts, FastFlow::NegativeRadius, FastFlow::SuccessfulIteration, and FastFlow::TruncationTol.
operator==()
bool operator== (const FastFlow & lhs, const FastFlow & rhs) noexcept
Referenced by operator<<(), and FastFlow::reset_for_next_find().