SpECTRE: Constant Expressions
Constant Expressions
Contains an assortment of constexpr functions.
Functions
template<typename List , Requires< not tt::is_a_v< tmpl::list, tmpl::front< List >>> = nullptr>
constexpr cpp17::array< std::decay_t< decltype(tmpl::front< List >::value)>, tmpl::size< List >::value > make_cpp17_array_from_list ()
Make an array from a typelist that holds std::integral_constant's all of which have the same value_type
template<typename T , Requires< tt::is_integer_v< T > and cpp17::is_unsigned_v< T >> = nullptr>
constexpr T two_to_the (T n)
Compute 2 to the n for integral types.
constexpr size_t get_nth_bit (const size_t i, const size_t N)
Get the nth bit from the right, counting from zero.
template<typename T >
decltype(auto) constexpr square (const T &x)
Compute the square of x
template<typename T >
decltype(auto) constexpr cube (const T &x)
Compute the cube of x
constexpr uint64_t falling_factorial (const uint64_t x, const uint64_t n) noexcept
Compute the falling factorial of \((x)_{n}\).
constexpr uint64_t factorial (const uint64_t n) noexcept
Compute the factorial of \(n!\).
template<int N, typename T >
decltype(auto) constexpr pow (const T &t)
Compute t^N where N is an integer (positive or negative)
template<typename T , Requires< tt::is_integer_v< T > or cpp17::is_floating_point_v< T >> = nullptr>
constexpr T ce_abs (const T &x) noexcept(noexcept(x< 0 ? -x :x))
Compute the absolute value of of its argument.
constexpr double ce_fabs (const double x) noexcept
Compute the absolute value of its argument.
template<size_t NumTerms, typename Function , Requires< NumTerms==1 > = nullptr>
decltype(auto) constexpr constexpr_sum (Function &&f) noexcept
Returns f(ic<0>{}) + f(ic<1>{}) + ... + f(ic<NumTerms-1>{}) where ic<N> stands for std::integral_constant<size_t, N>. This function allows the result types of each operation to be different, and so works efficiently with expression templates.
template<typename List , Requires< not tt::is_a_v< tmpl::list, tmpl::front< List >>> = nullptr>
constexpr std::array< std::decay_t< decltype(tmpl::front< List >::value)>, tmpl::size< List >::value > make_array_from_list ()
Make an array from a typelist that holds std::integral_constant's all of which have the same value_type
constexpr size_t cstring_length (const char *str) noexcept
Compute the length of a const char* at compile time.
constexpr size_t cstring_hash (const char *str) noexcept
Compute a hash of a const char* at compile time.
template<size_t I, typename T , size_t Size>
constexpr std::array< std::decay_t< T >, Size > replace_at (const std::array< T, Size > &arr, T value)
Replace at compile time the Ith entry in the array with value
template<typename T , typename S , size_t size>
constexpr bool array_equal (const std::array< T, size > &lhs, const std::array< S, size > &rhs, const size_t i=0) noexcept
Check at compile time if two std::arrays are equal.
template<typename T >
constexpr const T & cpp17::as_const (const T &t) noexcept
Returns a const reference to its argument.
template<typename T >
constexpr const T & max_by_magnitude (const T &a, const T &b)
Return the argument with the largest magnitude.
template<typename T >
constexpr T max_by_magnitude (std::initializer_list< T > ilist)
Return the argument with the largest magnitude.
template<typename T >
constexpr const T & min_by_magnitude (const T &a, const T &b)
Return the argument with the smallest magnitude.
template<typename T >
constexpr T min_by_magnitude (std::initializer_list< T > ilist)
Return the argument with the smallest magnitude.
Detailed Description
Contains an assortment of constexpr functions.
Description
Contains an assortment of constexpr functions that are useful for metaprogramming, or efficient mathematical computations, such as exponentiating to an integer power, where the power is known at compile time.
Function Documentation
array_equal()
template<typename T , typename S , size_t size> constexpr bool array_equal (const std::array< T, size > & lhs, const std::array< S, size > & rhs, const size_t i = 0) inline noexcept
Check at compile time if two std::arrays are equal.
as_const()
template<typename T > constexpr const T& cpp17::as_const (const T & t) noexcept
Returns a const reference to its argument.
Referenced by TimeSteppers::BoundaryHistory< LocalVars, RemoteVars, CouplingResult >::coupling(), and ActionTesting::ActionRunner< Metavariables >::is_ready().
ce_abs()
template<typename T , Requires< tt::is_integer_v< T > or cpp17::is_floating_point_v< T >> = nullptr> constexpr T ce_abs (const T & x) noexcept
Compute the absolute value of of its argument.
The argument must be comparable to an int and must be negatable.
References SPECTRE_ALWAYS_INLINE.
Referenced by ce_fabs().
ce_fabs()
constexpr double ce_fabs (const double x) noexcept
Compute the absolute value of its argument.
Referenced by equal_within_roundoff().
constexpr_sum()
template<size_t NumTerms, typename Function , Requires< NumTerms==1 > = nullptr> decltype(auto) constexpr constexpr_sum (Function && f) noexcept
Returns f(ic<0>{}) + f(ic<1>{}) + ... + f(ic<NumTerms-1>{}) where ic<N> stands for std::integral_constant<size_t, N>. This function allows the result types of each operation to be different, and so works efficiently with expression templates.
Note
When summing expression templates one must be careful of referring to temporaries in f.
cstring_hash()
constexpr size_t cstring_hash (const char * str) noexcept
Compute a hash of a const char* at compile time.
Referenced by db::get_tag_name().
cstring_length()
constexpr size_t cstring_length (const char * str) noexcept
Compute the length of a const char* at compile time.
cube()
template<typename T > decltype(auto) constexpr cube (const T & x)
Compute the cube of x
Referenced by EinsteinSolutions::KerrSchild::solution().
factorial()
constexpr uint64_t factorial (const uint64_t n) noexcept
Compute the factorial of \(n!\).
References db::apply(), falling_factorial(), pow(), and SPECTRE_ALWAYS_INLINE.
falling_factorial()
constexpr uint64_t falling_factorial (const uint64_t x, const uint64_t n) noexcept
Compute the falling factorial of \((x)_{n}\).
See http://mathworld.wolfram.com/FallingFactorial.html
Note
The largest representable factorial is 20!. It is up to the user to ensure this is satisfied
Referenced by factorial().
get_nth_bit()
constexpr size_t get_nth_bit (const size_t i, const size_t N)
Get the nth bit from the right, counting from zero.
Parameters
i the value to be acted on.
N which place to extract the bit
Returns: the value of the bit at that place.
make_array_from_list()
template<typename List , Requires< not tt::is_a_v< tmpl::list, tmpl::front< List >>> = nullptr> constexpr std::array<std::decay_t<decltype(tmpl::front<List>::value)>, tmpl::size<List>::value> make_array_from_list () inline
Make an array from a typelist that holds std::integral_constant's all of which have the same value_type
Template Parameters
List the typelist of std::integral_constant's
Returns: array of integral values from the typelist
Referenced by make_array_from_list().
make_cpp17_array_from_list()
template<typename List , Requires< not tt::is_a_v< tmpl::list, tmpl::front< List >>> = nullptr> constexpr cpp17::array<std::decay_t<decltype(tmpl::front<List>::value)>, tmpl::size<List>::value> make_cpp17_array_from_list () inline
Make an array from a typelist that holds std::integral_constant's all of which have the same value_type
Template Parameters
List the typelist of std::integral_constant's
Returns: array of integral values from the typelist
max_by_magnitude() [1/2]
template<typename T > constexpr const T& max_by_magnitude (const T & a, const T & b)
Return the argument with the largest magnitude.
Magnitude is determined by constexpr_abs. In case of a tie, returns the leftmost of the tied values.
max_by_magnitude() [2/2]
template<typename T > constexpr T max_by_magnitude (std::initializer_list< T > ilist)
Return the argument with the largest magnitude.
Magnitude is determined by constexpr_abs. In case of a tie, returns the leftmost of the tied values.
min_by_magnitude() [1/2]
template<typename T > constexpr const T& min_by_magnitude (const T & a, const T & b)
Return the argument with the smallest magnitude.
Magnitude is determined by constexpr_abs. In case of a tie, returns the leftmost of the tied values.
min_by_magnitude() [2/2]
template<typename T > constexpr T min_by_magnitude (std::initializer_list< T > ilist)
Return the argument with the smallest magnitude.
Magnitude is determined by constexpr_abs. In case of a tie, returns the leftmost of the tied values.
pow()
template<int N, typename T > decltype(auto) constexpr pow (const T & t)
Compute t^N where N is an integer (positive or negative)
Warning
If passing an integer this will do integer arithmatic, e.g. pow<-10>(2) == 0
Template Parameters
N the integer power being raised to in t^N
Parameters
t the value being exponentiated
Returns: value t^N of type T
References db::apply().
Referenced by MakeWithValueImpls::MakeWithValueImpl< R, T >::apply(), file_system::create_directory(), factorial(), DataVector::pow(), and MathFunctions::PowX::second_deriv().
replace_at()
template<size_t I, typename T , size_t Size> constexpr std::array<std::decay_t<T>, Size> replace_at (const std::array< T, Size > & arr, T value) inline
Replace at compile time the Ith entry in the array with value
square()
template<typename T > decltype(auto) constexpr square (const T & x)
Compute the square of x
Referenced by FastFlow::current_l_mesh(), ScalarWave::Solutions::PlaneWave< Dim >::d2psi_dt2(), StrahlkorperTags::InvHessian< Frame >::function(), StrahlkorperTags::D2xRadius< Frame >::function(), GeneralizedHarmonic::gauge_source(), YlmSpherepack::InterpolationInfoPerPoint::InterpolationInfoPerPoint(), CoordinateMaps::Equiangular::inv_jacobian(), CoordinateMaps::Wedge2D::inverse(), CoordinateMaps::Wedge3D::inverse(), CoordinateMaps::BulgedCube::inverse(), CoordinateMaps::Wedge2D::jacobian(), CoordinateMaps::Equiangular::jacobian(), CoordinateMaps::Wedge3D::jacobian(), magnitude(), CoordinateMaps::Wedge2D::operator()(), CoordinateMaps::Wedge3D::operator()(), CoordinateMaps::BulgedCube::operator()(), ContinuedFraction< T >::operator++(), StrahlkorperGr::ricci_scalar(), MathFunctions::Gaussian::second_deriv(), MathFunctions::Sinusoid::second_deriv(), and EinsteinSolutions::KerrSchild::solution().
two_to_the()
template<typename T , Requires< tt::is_integer_v< T > and cpp17::is_unsigned_v< T >> = nullptr> constexpr T two_to_the (T n)
Compute 2 to the n for integral types.
Parameters
n the power of two to compute.
Returns: 2^n
Referenced by StepControllers::BinaryFraction::choose_step(), SegmentId::endpoint(), SegmentId::id_if_flipped(), initial_element_ids< 1 >(), initial_element_ids< 2 >(), initial_element_ids< 3 >(), mean_value(), mean_value_on_boundary(), SegmentId::midpoint(), SegmentId::overlaps(), SegmentId::SegmentId(), SegmentIndex::SegmentIndex(), and set_internal_boundaries().