SpECTRE: src/Domain/InitialElementIds.cpp File Reference
InitialElementIds.cpp File Reference
#include "Domain/InitialElementIds.hpp"
#include <iterator>
#include "Domain/ElementId.hpp"
#include "Domain/SegmentId.hpp"
#include "Utilities/ConstantExpressions.hpp"
#include "Utilities/MakeArray.hpp"
Functions
template<>
std::vector< ElementId< 1 > > initial_element_ids< 1 > (const size_t block_id, const std::array< size_t, 1 > initial_ref_levs)
template<>
std::vector< ElementId< 2 > > initial_element_ids< 2 > (const size_t block_id, const std::array< size_t, 2 > initial_ref_levs)
template<>
std::vector< ElementId< 3 > > initial_element_ids< 3 > (const size_t block_id, const std::array< size_t, 3 > initial_ref_levs)
template<size_t VolumeDim>
std::vector< ElementId< VolumeDim > > initial_element_ids (const std::vector< std::array< size_t, VolumeDim >> &initial_refinement_levels) noexcept
Create the ElementIds of the initial computational domain.
template std::vector< ElementId< 1 > > initial_element_ids< 1 > (const std::vector< std::array< size_t, 1 >> &initial_refinement_levels) noexcept
template std::vector< ElementId< 2 > > initial_element_ids< 2 > (const std::vector< std::array< size_t, 2 >> &initial_refinement_levels) noexcept
template std::vector< ElementId< 3 > > initial_element_ids< 3 > (const std::vector< std::array< size_t, 3 >> &initial_refinement_levels) noexcept
Function Documentation
initial_element_ids< 1 >() [1/2]
template<> std::vector<ElementId<1> > initial_element_ids< 1 > (const size_t block_id, const std::array< size_t, 1 > initial_ref_levs)
References two_to_the().
Referenced by initial_element_ids().
initial_element_ids< 1 >() [2/2]
template std::vector<ElementId<1> > initial_element_ids< 1 > (const std::vector< std::array< size_t, 1 >> & initial_refinement_levels) noexcept
initial_element_ids< 2 >() [1/2]
template<> std::vector<ElementId<2> > initial_element_ids< 2 > (const size_t block_id, const std::array< size_t, 2 > initial_ref_levs)
References make_array(), and two_to_the().
Referenced by initial_element_ids().
initial_element_ids< 2 >() [2/2]
template std::vector<ElementId<2> > initial_element_ids< 2 > (const std::vector< std::array< size_t, 2 >> & initial_refinement_levels) noexcept
initial_element_ids< 3 >() [1/2]
template<> std::vector<ElementId<3> > initial_element_ids< 3 > (const size_t block_id, const std::array< size_t, 3 > initial_ref_levs)
References make_array(), and two_to_the().
Referenced by initial_element_ids().
initial_element_ids< 3 >() [2/2]
template std::vector<ElementId<3> > initial_element_ids< 3 > (const std::vector< std::array< size_t, 3 >> & initial_refinement_levels) noexcept