SpECTRE: DgElementArray< Metavariables, ActionList > Struct Template Reference
DgElementArray< Metavariables, ActionList > Struct Template Reference
#include <DgElementArray.hpp>
Public Types
using chare_type = Parallel::Algorithms::Array
using const_global_cache_tag_list = tmpl::flatten< tmpl::list< CacheTags::FinalTime, CacheTags::TimeStepper, typename Metavariables::dg_element_array_add_to_cache > >
using metavariables = Metavariables
using action_list = ActionList
using array_index = ElementIndex< volume_dim >
using explicit_single_actions_list = tmpl::list< dg::Actions::InitializeElement< volume_dim > >
using initial_databox = db::compute_databox_type< typename dg::Actions::InitializeElement< volume_dim >::template return_tag_list< typename Metavariables::system > >
using options = tmpl::list< typename Metavariables::domain_creator_tag, OptionTags::InitialTime, OptionTags::DeltaT >
Static Public Member Functions
static void initialize (Parallel::CProxy_ConstGlobalCache< Metavariables > &global_cache, std::unique_ptr< DomainCreator< volume_dim, Frame::Inertial >> domain_creator, double initial_time, double initial_dt) noexcept
static void execute_next_global_actions (const typename Metavariables::Phase next_phase, Parallel::CProxy_ConstGlobalCache< Metavariables > &global_cache)
Static Public Attributes
static constexpr size_t volume_dim = Metavariables::system::volume_dim
Member Typedef Documentation
action_list
template<class Metavariables , class ActionList > using DgElementArray< Metavariables, ActionList >::action_list = ActionList
array_index
template<class Metavariables , class ActionList > using DgElementArray< Metavariables, ActionList >::array_index = ElementIndex<volume_dim>
chare_type
template<class Metavariables , class ActionList > using DgElementArray< Metavariables, ActionList >::chare_type = Parallel::Algorithms::Array
const_global_cache_tag_list
template<class Metavariables , class ActionList > using DgElementArray< Metavariables, ActionList >::const_global_cache_tag_list = tmpl::flatten< tmpl::list<CacheTags::FinalTime, CacheTags::TimeStepper, typename Metavariables::dg_element_array_add_to_cache> >
explicit_single_actions_list
template<class Metavariables , class ActionList > using DgElementArray< Metavariables, ActionList >::explicit_single_actions_list = tmpl::list<dg::Actions::InitializeElement<volume_dim> >
initial_databox
template<class Metavariables , class ActionList > using DgElementArray< Metavariables, ActionList >::initial_databox = db::compute_databox_type< typename dg::Actions::InitializeElement<volume_dim>:: template return_tag_list<typename Metavariables::system> >
metavariables
template<class Metavariables , class ActionList > using DgElementArray< Metavariables, ActionList >::metavariables = Metavariables
options
template<class Metavariables , class ActionList > using DgElementArray< Metavariables, ActionList >::options = tmpl::list<typename Metavariables::domain_creator_tag, OptionTags::InitialTime, OptionTags::DeltaT>
Member Function Documentation
execute_next_global_actions()
template<class Metavariables , class ActionList > static void DgElementArray< Metavariables, ActionList >::execute_next_global_actions (const typename Metavariables::Phase next_phase, Parallel::CProxy_ConstGlobalCache< Metavariables > & global_cache) inline static
initialize()
template<class Metavariables , class ActionList > void DgElementArray< Metavariables, ActionList >::initialize (Parallel::CProxy_ConstGlobalCache< Metavariables > & global_cache, std::unique_ptr< DomainCreator< volume_dim, Frame::Inertial >> domain_creator, double initial_time, double initial_dt) static noexcept
References Slab::duration(), Slab::end(), initial_element_ids(), Parallel::number_of_procs(), Slab::start(), Slab::with_duration_from_start(), and Slab::with_duration_to_end().
Member Data Documentation
volume_dim
template<class Metavariables , class ActionList > constexpr size_t DgElementArray< Metavariables, ActionList >::volume_dim = Metavariables::system::volume_dim static
The documentation for this struct was generated from the following file:
src/Evolution/DiscontinuousGalerkin/DgElementArray.hpp