SpECTRE: dg::Actions::ComputeBoundaryFlux< Metavariables > Struct Template Reference
dg::Actions::ComputeBoundaryFlux< Metavariables > Struct Template Reference
#include <FluxCommunication2.hpp>
Classes
struct FluxesTag
Public Types
using PackagedData = Variables< typename Metavariables::normal_dot_numerical_flux::type::package_tags >
using system = typename Metavariables::system
using inbox_tags = tmpl::list< FluxesTag >
Static Public Member Functions
template<typename DbTags , typename... InboxTags, typename ArrayIndex , typename ActionList , typename ParallelComponent >
static auto apply (db::DataBox< DbTags > &box, tuples::TaggedTuple< InboxTags... > &inboxes, const Parallel::ConstGlobalCache< Metavariables > &cache, const ArrayIndex &, const ActionList, const ParallelComponent *const) noexcept
template<typename DbTags , typename... InboxTags, typename ArrayIndex >
static bool is_ready (const db::DataBox< DbTags > &box, const tuples::TaggedTuple< InboxTags... > &inboxes, const Parallel::ConstGlobalCache< Metavariables > &, const ArrayIndex &) noexcept
Static Public Attributes
static constexpr size_t volume_dim = system::volume_dim
Member Typedef Documentation
inbox_tags
template<typename Metavariables > using dg::Actions::ComputeBoundaryFlux< Metavariables >::inbox_tags = tmpl::list<FluxesTag>
PackagedData
template<typename Metavariables > using dg::Actions::ComputeBoundaryFlux< Metavariables >::PackagedData = Variables< typename Metavariables::normal_dot_numerical_flux::type::package_tags>
system
template<typename Metavariables > using dg::Actions::ComputeBoundaryFlux< Metavariables >::system = typename Metavariables::system
Member Function Documentation
apply()
template<typename Metavariables > template<typename DbTags , typename... InboxTags, typename ArrayIndex , typename ActionList , typename ParallelComponent > static auto dg::Actions::ComputeBoundaryFlux< Metavariables >::apply (db::DataBox< DbTags > & box, tuples::TaggedTuple< InboxTags... > & inboxes, const Parallel::ConstGlobalCache< Metavariables > & cache, const ArrayIndex & , const ActionList , const ParallelComponent * const) inline static noexcept
References add_slice_to_data(), ASSERT, gsl::at(), db::create_from(), keys_of(), dg::lift_flux(), Lower, magnitude(), and make_not_null().
is_ready()
template<typename Metavariables > template<typename DbTags , typename... InboxTags, typename ArrayIndex > static bool dg::Actions::ComputeBoundaryFlux< Metavariables >::is_ready (const db::DataBox< DbTags > & box, const tuples::TaggedTuple< InboxTags... > & inboxes, const Parallel::ConstGlobalCache< Metavariables > & , const ArrayIndex &) inline static noexcept
Member Data Documentation
volume_dim
template<typename Metavariables > constexpr size_t dg::Actions::ComputeBoundaryFlux< Metavariables >::volume_dim = system::volume_dim static
The documentation for this struct was generated from the following file:
src/NumericalAlgorithms/DiscontinuousGalerkin/Actions/FluxCommunication2.hpp