SpECTRE: dg::Actions::SendDataForFluxes Struct Reference
dg::Actions::SendDataForFluxes Struct Reference
#include <FluxCommunication2.hpp>
Static Public Member Functions
template<typename DbTags , typename... InboxTags, typename Metavariables , typename ArrayIndex , typename ActionList , typename ParallelComponent >
static auto apply (db::DataBox< DbTags > &box, tuples::TaggedTuple< InboxTags... > &, Parallel::ConstGlobalCache< Metavariables > &cache, const ArrayIndex &, const ActionList, const ParallelComponent *const) noexcept
Member Function Documentation
apply()
template<typename DbTags , typename... InboxTags, typename Metavariables , typename ArrayIndex , typename ActionList , typename ParallelComponent > static auto dg::Actions::SendDataForFluxes::apply (db::DataBox< DbTags > & box, tuples::TaggedTuple< InboxTags... > & , Parallel::ConstGlobalCache< Metavariables > & cache, const ArrayIndex & , const ActionList , const ParallelComponent * const) inline static noexcept
References ASSERT, gsl::at(), db::create_from(), db::data_on_slice(), Lower, magnitude(), make_not_null(), orient_variables_on_slice(), and DataVector::size().
The documentation for this struct was generated from the following file:
src/NumericalAlgorithms/DiscontinuousGalerkin/Actions/FluxCommunication2.hpp