SpECTRE: dg::Actions::InitializeElement< Dim > Struct Template Reference
dg::Actions::InitializeElement< Dim > Struct Template Reference
Actions | Discontinuous Galerkin
Initialize a dG element with analytic initial data.
#include <InitializeElement.hpp>
Public Types
using apply_args = tmpl::list< std::vector< std::array< size_t, Dim > >, Domain< Dim, Frame::Inertial >, ::Time, ::TimeDelta >
template<class System >
using return_tag_list = tmpl::list< Tags::TimeId, Tags::Time, Tags::TimeStep, Tags::LogicalCoordinates< Dim >, Tags::Extents< Dim >, Tags::Element< Dim >, Tags::ElementMap< Dim >, typename System::variables_tag, Tags::HistoryEvolvedVariables< typename System::variables_tag, db::add_tag_prefix< Tags::dt, typename System::variables_tag > >, Tags::Coordinates< Tags::ElementMap< Dim >, Tags::LogicalCoordinates< Dim > >, Tags::InverseJacobian< Tags::ElementMap< Dim >, Tags::LogicalCoordinates< Dim > >, Tags::deriv< typename System::variables_tag::tags_list, typename System::gradients_tags, Tags::InverseJacobian< Tags::ElementMap< Dim >, Tags::LogicalCoordinates< Dim > >>, db::add_tag_prefix< Tags::dt, typename System::variables_tag >, Tags::UnnormalizedFaceNormal< Dim > >
Static Public Member Functions
template<typename... InboxTags, typename Metavariables , typename ActionList , typename ParallelComponent >
static auto apply (const db::DataBox< tmpl::list<>> &, const tuples::TaggedTuple< InboxTags... > &, const Parallel::ConstGlobalCache< Metavariables > &cache, const ElementIndex< Dim > &array_index, const ActionList, const ParallelComponent *const, std::vector< std::array< size_t, Dim >> initial_extents, Domain< Dim, Frame::Inertial > domain, Time initial_time, TimeDelta initial_dt) noexcept
Detailed Description
template<size_t Dim>
struct dg::Actions::InitializeElement< Dim >
Initialize a dG element with analytic initial data.
Uses:
ConstGlobalCache:
A tag deriving off of Cache::AnalyticSolutionBase
CacheTags::TimeStepper
DataBox changes:
Adds:
Tags::TimeId
Tags::Time
Tags::TimeStep
Tags::LogicalCoordinates<Dim>
Tags::Extents<Dim>
Tags::Element<Dim>
Tags::ElementMap<Dim>
System::variables_tag
Tags::HistoryEvolvedVariables<System::variables_tag, db::add_tag_prefix<Tags::dt, System::variables_tag>>
Tags::Coordinates<Tags::ElementMap<Dim>, Tags::LogicalCoordinates<Dim>>
Tags::InverseJacobian<Tags::ElementMap<Dim>, Tags::LogicalCoordinates<Dim>>
Tags::deriv<System::variables_tag::tags_list, System::gradients_tags, Tags::InverseJacobian<Tags::ElementMap<Dim>, Tags::LogicalCoordinates<Dim>>>
db::add_tag_prefix<Tags::dt, System::variables_tag>
Tags::UnnormalizedFaceNormal<Dim>
Removes: nothing
Modifies: nothing
Member Typedef Documentation
apply_args
template<size_t Dim> using dg::Actions::InitializeElement< Dim >::apply_args = tmpl::list<std::vector<std::array<size_t, Dim> >, Domain<Dim, Frame::Inertial>, ::Time, ::TimeDelta>
return_tag_list
template<size_t Dim> template<class System > using dg::Actions::InitializeElement< Dim >::return_tag_list = tmpl::list< Tags::TimeId, Tags::Time, Tags::TimeStep, Tags::LogicalCoordinates<Dim>, Tags::Extents<Dim>, Tags::Element<Dim>, Tags::ElementMap<Dim>, typename System::variables_tag, Tags::HistoryEvolvedVariables< typename System::variables_tag, db::add_tag_prefix<Tags::dt, typename System::variables_tag> >, Tags::Coordinates<Tags::ElementMap<Dim>, Tags::LogicalCoordinates<Dim> >, Tags::InverseJacobian<Tags::ElementMap<Dim>, Tags::LogicalCoordinates<Dim> >, Tags::deriv<typename System::variables_tag::tags_list, typename System::gradients_tags, Tags::InverseJacobian<Tags::ElementMap<Dim>, Tags::LogicalCoordinates<Dim> >>, db::add_tag_prefix<Tags::dt, typename System::variables_tag>, Tags::UnnormalizedFaceNormal<Dim> >
Member Function Documentation
apply()
template<size_t Dim> template<typename... InboxTags, typename Metavariables , typename ActionList , typename ParallelComponent > static auto dg::Actions::InitializeElement< Dim >::apply (const db::DataBox< tmpl::list<>> & , const tuples::TaggedTuple< InboxTags... > & , const Parallel::ConstGlobalCache< Metavariables > & cache, const ElementIndex< Dim > & array_index, const ActionList , const ParallelComponent * const, std::vector< std::array< size_t, Dim >> initial_extents, Domain< Dim, Frame::Inertial > domain, Time initial_time, TimeDelta initial_dt) inline static noexcept
References Slab::advance_towards(), db::create(), create_initial_element(), logical_coordinates(), Index< Dim >::product(), TimeDelta::slab(), TimeId::time, Time::value(), and TimeDelta::with_slab().
The documentation for this struct was generated from the following file:
src/Evolution/DiscontinuousGalerkin/InitializeElement.hpp