SpECTRE: create_from_yaml< FastFlow::FlowType > Struct Template Reference
create_from_yaml< FastFlow::FlowType > Struct Template Reference
#include <FastFlow.hpp>
Static Public Member Functions
static FastFlow::FlowType create (const Option &options)
Member Function Documentation
create()
FastFlow::FlowType create_from_yaml< FastFlow::FlowType >::create (const Option & options) static
References Option::context(), FastFlow::current_l_mesh(), FastFlow::Curvature, StrahlkorperGr::extrinsic_curvature(), FastFlow::Fast, FastFlow::Jacobi, Option::parse_as(), and PARSE_ERROR.
The documentation for this struct was generated from the following files:
src/ApparentHorizons/FastFlow.hpp
src/ApparentHorizons/FastFlow.cpp